/*
Relentless Identity API

Testing FinderAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package relentlessidentity

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "go.relentlessidentity.com/sdk"
)

func Test_relentlessidentity_FinderAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FinderAPIService FinderAttempt", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FinderAPI.FinderAttempt(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
