/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClientBatchIdentityResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientBatchIdentityResponse{}

// ClientBatchIdentityResponse Synchronous batch Probe response with compact per-item results and a small summary block.
type ClientBatchIdentityResponse struct {
	// Per-email compact probe results in request order.
	Results []ClientIdentityResponse `json:"results"`
	Summary BatchSummary `json:"summary"`
}

type _ClientBatchIdentityResponse ClientBatchIdentityResponse

// NewClientBatchIdentityResponse instantiates a new ClientBatchIdentityResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientBatchIdentityResponse(results []ClientIdentityResponse, summary BatchSummary) *ClientBatchIdentityResponse {
	this := ClientBatchIdentityResponse{}
	this.Results = results
	this.Summary = summary
	return &this
}

// NewClientBatchIdentityResponseWithDefaults instantiates a new ClientBatchIdentityResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientBatchIdentityResponseWithDefaults() *ClientBatchIdentityResponse {
	this := ClientBatchIdentityResponse{}
	return &this
}

// GetResults returns the Results field value
func (o *ClientBatchIdentityResponse) GetResults() []ClientIdentityResponse {
	if o == nil {
		var ret []ClientIdentityResponse
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *ClientBatchIdentityResponse) GetResultsOk() ([]ClientIdentityResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *ClientBatchIdentityResponse) SetResults(v []ClientIdentityResponse) {
	o.Results = v
}

// GetSummary returns the Summary field value
func (o *ClientBatchIdentityResponse) GetSummary() BatchSummary {
	if o == nil {
		var ret BatchSummary
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *ClientBatchIdentityResponse) GetSummaryOk() (*BatchSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *ClientBatchIdentityResponse) SetSummary(v BatchSummary) {
	o.Summary = v
}

func (o ClientBatchIdentityResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientBatchIdentityResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results
	toSerialize["summary"] = o.Summary
	return toSerialize, nil
}

func (o *ClientBatchIdentityResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
		"summary",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientBatchIdentityResponse := _ClientBatchIdentityResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClientBatchIdentityResponse)

	if err != nil {
		return err
	}

	*o = ClientBatchIdentityResponse(varClientBatchIdentityResponse)

	return err
}

type NullableClientBatchIdentityResponse struct {
	value *ClientBatchIdentityResponse
	isSet bool
}

func (v NullableClientBatchIdentityResponse) Get() *ClientBatchIdentityResponse {
	return v.value
}

func (v *NullableClientBatchIdentityResponse) Set(val *ClientBatchIdentityResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientBatchIdentityResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientBatchIdentityResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientBatchIdentityResponse(val *ClientBatchIdentityResponse) *NullableClientBatchIdentityResponse {
	return &NullableClientBatchIdentityResponse{value: val, isSet: true}
}

func (v NullableClientBatchIdentityResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientBatchIdentityResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


