/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClientUsageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientUsageResponse{}

// ClientUsageResponse Current authenticated account usage, free-tier windows, and paid balance snapshot.
type ClientUsageResponse struct {
	// Current plan family, such as free or paid.
	PlanTier string `json:"plan_tier"`
	BillingMode string `json:"billing_mode"`
	BillingStatus NullableString `json:"billing_status,omitempty"`
	FreeWindowLimit int32 `json:"free_window_limit"`
	FreeWindowHours int32 `json:"free_window_hours"`
	FreeWeeklyLimit int32 `json:"free_weekly_limit"`
	WindowRequestsUsed int32 `json:"window_requests_used"`
	WeeklyRequestsUsed int32 `json:"weekly_requests_used"`
	WindowRequestsRemaining int32 `json:"window_requests_remaining"`
	WeeklyRequestsRemaining int32 `json:"weekly_requests_remaining"`
	BillingCycleValueMicros NullableInt32 `json:"billing_cycle_value_micros,omitempty"`
	BillingExtraValueMicros int32 `json:"billing_extra_value_micros"`
	BillingValueMicrosUsed int32 `json:"billing_value_micros_used"`
	// Paid usage value currently reserved by queued or running background jobs.
	BillingValueMicrosReserved *int32 `json:"billing_value_micros_reserved,omitempty"`
	BillingValueMicrosRemaining NullableInt32 `json:"billing_value_micros_remaining,omitempty"`
	UsagePercentRemaining NullableFloat32 `json:"usage_percent_remaining,omitempty"`
	CurrentPlanFinderDeliverableCostMicros NullableInt32 `json:"current_plan_finder_deliverable_cost_micros,omitempty"`
	CurrentPlanFinderUndeliverableCostMicros NullableInt32 `json:"current_plan_finder_undeliverable_cost_micros,omitempty"`
	CurrentPlanProbeCostMicros NullableInt32 `json:"current_plan_probe_cost_micros,omitempty"`
}

type _ClientUsageResponse ClientUsageResponse

// NewClientUsageResponse instantiates a new ClientUsageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientUsageResponse(planTier string, billingMode string, freeWindowLimit int32, freeWindowHours int32, freeWeeklyLimit int32, windowRequestsUsed int32, weeklyRequestsUsed int32, windowRequestsRemaining int32, weeklyRequestsRemaining int32, billingExtraValueMicros int32, billingValueMicrosUsed int32) *ClientUsageResponse {
	this := ClientUsageResponse{}
	this.PlanTier = planTier
	this.BillingMode = billingMode
	this.FreeWindowLimit = freeWindowLimit
	this.FreeWindowHours = freeWindowHours
	this.FreeWeeklyLimit = freeWeeklyLimit
	this.WindowRequestsUsed = windowRequestsUsed
	this.WeeklyRequestsUsed = weeklyRequestsUsed
	this.WindowRequestsRemaining = windowRequestsRemaining
	this.WeeklyRequestsRemaining = weeklyRequestsRemaining
	this.BillingExtraValueMicros = billingExtraValueMicros
	this.BillingValueMicrosUsed = billingValueMicrosUsed
	return &this
}

// NewClientUsageResponseWithDefaults instantiates a new ClientUsageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientUsageResponseWithDefaults() *ClientUsageResponse {
	this := ClientUsageResponse{}
	return &this
}

// GetPlanTier returns the PlanTier field value
func (o *ClientUsageResponse) GetPlanTier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanTier
}

// GetPlanTierOk returns a tuple with the PlanTier field value
// and a boolean to check if the value has been set.
func (o *ClientUsageResponse) GetPlanTierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanTier, true
}

// SetPlanTier sets field value
func (o *ClientUsageResponse) SetPlanTier(v string) {
	o.PlanTier = v
}

// GetBillingMode returns the BillingMode field value
func (o *ClientUsageResponse) GetBillingMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BillingMode
}

// GetBillingModeOk returns a tuple with the BillingMode field value
// and a boolean to check if the value has been set.
func (o *ClientUsageResponse) GetBillingModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingMode, true
}

// SetBillingMode sets field value
func (o *ClientUsageResponse) SetBillingMode(v string) {
	o.BillingMode = v
}

// GetBillingStatus returns the BillingStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientUsageResponse) GetBillingStatus() string {
	if o == nil || IsNil(o.BillingStatus.Get()) {
		var ret string
		return ret
	}
	return *o.BillingStatus.Get()
}

// GetBillingStatusOk returns a tuple with the BillingStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientUsageResponse) GetBillingStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BillingStatus.Get(), o.BillingStatus.IsSet()
}

// HasBillingStatus returns a boolean if a field has been set.
func (o *ClientUsageResponse) HasBillingStatus() bool {
	if o != nil && o.BillingStatus.IsSet() {
		return true
	}

	return false
}

// SetBillingStatus gets a reference to the given NullableString and assigns it to the BillingStatus field.
func (o *ClientUsageResponse) SetBillingStatus(v string) {
	o.BillingStatus.Set(&v)
}
// SetBillingStatusNil sets the value for BillingStatus to be an explicit nil
func (o *ClientUsageResponse) SetBillingStatusNil() {
	o.BillingStatus.Set(nil)
}

// UnsetBillingStatus ensures that no value is present for BillingStatus, not even an explicit nil
func (o *ClientUsageResponse) UnsetBillingStatus() {
	o.BillingStatus.Unset()
}

// GetFreeWindowLimit returns the FreeWindowLimit field value
func (o *ClientUsageResponse) GetFreeWindowLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FreeWindowLimit
}

// GetFreeWindowLimitOk returns a tuple with the FreeWindowLimit field value
// and a boolean to check if the value has been set.
func (o *ClientUsageResponse) GetFreeWindowLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FreeWindowLimit, true
}

// SetFreeWindowLimit sets field value
func (o *ClientUsageResponse) SetFreeWindowLimit(v int32) {
	o.FreeWindowLimit = v
}

// GetFreeWindowHours returns the FreeWindowHours field value
func (o *ClientUsageResponse) GetFreeWindowHours() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FreeWindowHours
}

// GetFreeWindowHoursOk returns a tuple with the FreeWindowHours field value
// and a boolean to check if the value has been set.
func (o *ClientUsageResponse) GetFreeWindowHoursOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FreeWindowHours, true
}

// SetFreeWindowHours sets field value
func (o *ClientUsageResponse) SetFreeWindowHours(v int32) {
	o.FreeWindowHours = v
}

// GetFreeWeeklyLimit returns the FreeWeeklyLimit field value
func (o *ClientUsageResponse) GetFreeWeeklyLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FreeWeeklyLimit
}

// GetFreeWeeklyLimitOk returns a tuple with the FreeWeeklyLimit field value
// and a boolean to check if the value has been set.
func (o *ClientUsageResponse) GetFreeWeeklyLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FreeWeeklyLimit, true
}

// SetFreeWeeklyLimit sets field value
func (o *ClientUsageResponse) SetFreeWeeklyLimit(v int32) {
	o.FreeWeeklyLimit = v
}

// GetWindowRequestsUsed returns the WindowRequestsUsed field value
func (o *ClientUsageResponse) GetWindowRequestsUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WindowRequestsUsed
}

// GetWindowRequestsUsedOk returns a tuple with the WindowRequestsUsed field value
// and a boolean to check if the value has been set.
func (o *ClientUsageResponse) GetWindowRequestsUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WindowRequestsUsed, true
}

// SetWindowRequestsUsed sets field value
func (o *ClientUsageResponse) SetWindowRequestsUsed(v int32) {
	o.WindowRequestsUsed = v
}

// GetWeeklyRequestsUsed returns the WeeklyRequestsUsed field value
func (o *ClientUsageResponse) GetWeeklyRequestsUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WeeklyRequestsUsed
}

// GetWeeklyRequestsUsedOk returns a tuple with the WeeklyRequestsUsed field value
// and a boolean to check if the value has been set.
func (o *ClientUsageResponse) GetWeeklyRequestsUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WeeklyRequestsUsed, true
}

// SetWeeklyRequestsUsed sets field value
func (o *ClientUsageResponse) SetWeeklyRequestsUsed(v int32) {
	o.WeeklyRequestsUsed = v
}

// GetWindowRequestsRemaining returns the WindowRequestsRemaining field value
func (o *ClientUsageResponse) GetWindowRequestsRemaining() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WindowRequestsRemaining
}

// GetWindowRequestsRemainingOk returns a tuple with the WindowRequestsRemaining field value
// and a boolean to check if the value has been set.
func (o *ClientUsageResponse) GetWindowRequestsRemainingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WindowRequestsRemaining, true
}

// SetWindowRequestsRemaining sets field value
func (o *ClientUsageResponse) SetWindowRequestsRemaining(v int32) {
	o.WindowRequestsRemaining = v
}

// GetWeeklyRequestsRemaining returns the WeeklyRequestsRemaining field value
func (o *ClientUsageResponse) GetWeeklyRequestsRemaining() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WeeklyRequestsRemaining
}

// GetWeeklyRequestsRemainingOk returns a tuple with the WeeklyRequestsRemaining field value
// and a boolean to check if the value has been set.
func (o *ClientUsageResponse) GetWeeklyRequestsRemainingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WeeklyRequestsRemaining, true
}

// SetWeeklyRequestsRemaining sets field value
func (o *ClientUsageResponse) SetWeeklyRequestsRemaining(v int32) {
	o.WeeklyRequestsRemaining = v
}

// GetBillingCycleValueMicros returns the BillingCycleValueMicros field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientUsageResponse) GetBillingCycleValueMicros() int32 {
	if o == nil || IsNil(o.BillingCycleValueMicros.Get()) {
		var ret int32
		return ret
	}
	return *o.BillingCycleValueMicros.Get()
}

// GetBillingCycleValueMicrosOk returns a tuple with the BillingCycleValueMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientUsageResponse) GetBillingCycleValueMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BillingCycleValueMicros.Get(), o.BillingCycleValueMicros.IsSet()
}

// HasBillingCycleValueMicros returns a boolean if a field has been set.
func (o *ClientUsageResponse) HasBillingCycleValueMicros() bool {
	if o != nil && o.BillingCycleValueMicros.IsSet() {
		return true
	}

	return false
}

// SetBillingCycleValueMicros gets a reference to the given NullableInt32 and assigns it to the BillingCycleValueMicros field.
func (o *ClientUsageResponse) SetBillingCycleValueMicros(v int32) {
	o.BillingCycleValueMicros.Set(&v)
}
// SetBillingCycleValueMicrosNil sets the value for BillingCycleValueMicros to be an explicit nil
func (o *ClientUsageResponse) SetBillingCycleValueMicrosNil() {
	o.BillingCycleValueMicros.Set(nil)
}

// UnsetBillingCycleValueMicros ensures that no value is present for BillingCycleValueMicros, not even an explicit nil
func (o *ClientUsageResponse) UnsetBillingCycleValueMicros() {
	o.BillingCycleValueMicros.Unset()
}

// GetBillingExtraValueMicros returns the BillingExtraValueMicros field value
func (o *ClientUsageResponse) GetBillingExtraValueMicros() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BillingExtraValueMicros
}

// GetBillingExtraValueMicrosOk returns a tuple with the BillingExtraValueMicros field value
// and a boolean to check if the value has been set.
func (o *ClientUsageResponse) GetBillingExtraValueMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingExtraValueMicros, true
}

// SetBillingExtraValueMicros sets field value
func (o *ClientUsageResponse) SetBillingExtraValueMicros(v int32) {
	o.BillingExtraValueMicros = v
}

// GetBillingValueMicrosUsed returns the BillingValueMicrosUsed field value
func (o *ClientUsageResponse) GetBillingValueMicrosUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BillingValueMicrosUsed
}

// GetBillingValueMicrosUsedOk returns a tuple with the BillingValueMicrosUsed field value
// and a boolean to check if the value has been set.
func (o *ClientUsageResponse) GetBillingValueMicrosUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingValueMicrosUsed, true
}

// SetBillingValueMicrosUsed sets field value
func (o *ClientUsageResponse) SetBillingValueMicrosUsed(v int32) {
	o.BillingValueMicrosUsed = v
}

// GetBillingValueMicrosReserved returns the BillingValueMicrosReserved field value if set, zero value otherwise.
func (o *ClientUsageResponse) GetBillingValueMicrosReserved() int32 {
	if o == nil || IsNil(o.BillingValueMicrosReserved) {
		var ret int32
		return ret
	}
	return *o.BillingValueMicrosReserved
}

// GetBillingValueMicrosReservedOk returns a tuple with the BillingValueMicrosReserved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientUsageResponse) GetBillingValueMicrosReservedOk() (*int32, bool) {
	if o == nil || IsNil(o.BillingValueMicrosReserved) {
		return nil, false
	}
	return o.BillingValueMicrosReserved, true
}

// HasBillingValueMicrosReserved returns a boolean if a field has been set.
func (o *ClientUsageResponse) HasBillingValueMicrosReserved() bool {
	if o != nil && !IsNil(o.BillingValueMicrosReserved) {
		return true
	}

	return false
}

// SetBillingValueMicrosReserved gets a reference to the given int32 and assigns it to the BillingValueMicrosReserved field.
func (o *ClientUsageResponse) SetBillingValueMicrosReserved(v int32) {
	o.BillingValueMicrosReserved = &v
}

// GetBillingValueMicrosRemaining returns the BillingValueMicrosRemaining field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientUsageResponse) GetBillingValueMicrosRemaining() int32 {
	if o == nil || IsNil(o.BillingValueMicrosRemaining.Get()) {
		var ret int32
		return ret
	}
	return *o.BillingValueMicrosRemaining.Get()
}

// GetBillingValueMicrosRemainingOk returns a tuple with the BillingValueMicrosRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientUsageResponse) GetBillingValueMicrosRemainingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BillingValueMicrosRemaining.Get(), o.BillingValueMicrosRemaining.IsSet()
}

// HasBillingValueMicrosRemaining returns a boolean if a field has been set.
func (o *ClientUsageResponse) HasBillingValueMicrosRemaining() bool {
	if o != nil && o.BillingValueMicrosRemaining.IsSet() {
		return true
	}

	return false
}

// SetBillingValueMicrosRemaining gets a reference to the given NullableInt32 and assigns it to the BillingValueMicrosRemaining field.
func (o *ClientUsageResponse) SetBillingValueMicrosRemaining(v int32) {
	o.BillingValueMicrosRemaining.Set(&v)
}
// SetBillingValueMicrosRemainingNil sets the value for BillingValueMicrosRemaining to be an explicit nil
func (o *ClientUsageResponse) SetBillingValueMicrosRemainingNil() {
	o.BillingValueMicrosRemaining.Set(nil)
}

// UnsetBillingValueMicrosRemaining ensures that no value is present for BillingValueMicrosRemaining, not even an explicit nil
func (o *ClientUsageResponse) UnsetBillingValueMicrosRemaining() {
	o.BillingValueMicrosRemaining.Unset()
}

// GetUsagePercentRemaining returns the UsagePercentRemaining field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientUsageResponse) GetUsagePercentRemaining() float32 {
	if o == nil || IsNil(o.UsagePercentRemaining.Get()) {
		var ret float32
		return ret
	}
	return *o.UsagePercentRemaining.Get()
}

// GetUsagePercentRemainingOk returns a tuple with the UsagePercentRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientUsageResponse) GetUsagePercentRemainingOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.UsagePercentRemaining.Get(), o.UsagePercentRemaining.IsSet()
}

// HasUsagePercentRemaining returns a boolean if a field has been set.
func (o *ClientUsageResponse) HasUsagePercentRemaining() bool {
	if o != nil && o.UsagePercentRemaining.IsSet() {
		return true
	}

	return false
}

// SetUsagePercentRemaining gets a reference to the given NullableFloat32 and assigns it to the UsagePercentRemaining field.
func (o *ClientUsageResponse) SetUsagePercentRemaining(v float32) {
	o.UsagePercentRemaining.Set(&v)
}
// SetUsagePercentRemainingNil sets the value for UsagePercentRemaining to be an explicit nil
func (o *ClientUsageResponse) SetUsagePercentRemainingNil() {
	o.UsagePercentRemaining.Set(nil)
}

// UnsetUsagePercentRemaining ensures that no value is present for UsagePercentRemaining, not even an explicit nil
func (o *ClientUsageResponse) UnsetUsagePercentRemaining() {
	o.UsagePercentRemaining.Unset()
}

// GetCurrentPlanFinderDeliverableCostMicros returns the CurrentPlanFinderDeliverableCostMicros field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientUsageResponse) GetCurrentPlanFinderDeliverableCostMicros() int32 {
	if o == nil || IsNil(o.CurrentPlanFinderDeliverableCostMicros.Get()) {
		var ret int32
		return ret
	}
	return *o.CurrentPlanFinderDeliverableCostMicros.Get()
}

// GetCurrentPlanFinderDeliverableCostMicrosOk returns a tuple with the CurrentPlanFinderDeliverableCostMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientUsageResponse) GetCurrentPlanFinderDeliverableCostMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentPlanFinderDeliverableCostMicros.Get(), o.CurrentPlanFinderDeliverableCostMicros.IsSet()
}

// HasCurrentPlanFinderDeliverableCostMicros returns a boolean if a field has been set.
func (o *ClientUsageResponse) HasCurrentPlanFinderDeliverableCostMicros() bool {
	if o != nil && o.CurrentPlanFinderDeliverableCostMicros.IsSet() {
		return true
	}

	return false
}

// SetCurrentPlanFinderDeliverableCostMicros gets a reference to the given NullableInt32 and assigns it to the CurrentPlanFinderDeliverableCostMicros field.
func (o *ClientUsageResponse) SetCurrentPlanFinderDeliverableCostMicros(v int32) {
	o.CurrentPlanFinderDeliverableCostMicros.Set(&v)
}
// SetCurrentPlanFinderDeliverableCostMicrosNil sets the value for CurrentPlanFinderDeliverableCostMicros to be an explicit nil
func (o *ClientUsageResponse) SetCurrentPlanFinderDeliverableCostMicrosNil() {
	o.CurrentPlanFinderDeliverableCostMicros.Set(nil)
}

// UnsetCurrentPlanFinderDeliverableCostMicros ensures that no value is present for CurrentPlanFinderDeliverableCostMicros, not even an explicit nil
func (o *ClientUsageResponse) UnsetCurrentPlanFinderDeliverableCostMicros() {
	o.CurrentPlanFinderDeliverableCostMicros.Unset()
}

// GetCurrentPlanFinderUndeliverableCostMicros returns the CurrentPlanFinderUndeliverableCostMicros field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientUsageResponse) GetCurrentPlanFinderUndeliverableCostMicros() int32 {
	if o == nil || IsNil(o.CurrentPlanFinderUndeliverableCostMicros.Get()) {
		var ret int32
		return ret
	}
	return *o.CurrentPlanFinderUndeliverableCostMicros.Get()
}

// GetCurrentPlanFinderUndeliverableCostMicrosOk returns a tuple with the CurrentPlanFinderUndeliverableCostMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientUsageResponse) GetCurrentPlanFinderUndeliverableCostMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentPlanFinderUndeliverableCostMicros.Get(), o.CurrentPlanFinderUndeliverableCostMicros.IsSet()
}

// HasCurrentPlanFinderUndeliverableCostMicros returns a boolean if a field has been set.
func (o *ClientUsageResponse) HasCurrentPlanFinderUndeliverableCostMicros() bool {
	if o != nil && o.CurrentPlanFinderUndeliverableCostMicros.IsSet() {
		return true
	}

	return false
}

// SetCurrentPlanFinderUndeliverableCostMicros gets a reference to the given NullableInt32 and assigns it to the CurrentPlanFinderUndeliverableCostMicros field.
func (o *ClientUsageResponse) SetCurrentPlanFinderUndeliverableCostMicros(v int32) {
	o.CurrentPlanFinderUndeliverableCostMicros.Set(&v)
}
// SetCurrentPlanFinderUndeliverableCostMicrosNil sets the value for CurrentPlanFinderUndeliverableCostMicros to be an explicit nil
func (o *ClientUsageResponse) SetCurrentPlanFinderUndeliverableCostMicrosNil() {
	o.CurrentPlanFinderUndeliverableCostMicros.Set(nil)
}

// UnsetCurrentPlanFinderUndeliverableCostMicros ensures that no value is present for CurrentPlanFinderUndeliverableCostMicros, not even an explicit nil
func (o *ClientUsageResponse) UnsetCurrentPlanFinderUndeliverableCostMicros() {
	o.CurrentPlanFinderUndeliverableCostMicros.Unset()
}

// GetCurrentPlanProbeCostMicros returns the CurrentPlanProbeCostMicros field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientUsageResponse) GetCurrentPlanProbeCostMicros() int32 {
	if o == nil || IsNil(o.CurrentPlanProbeCostMicros.Get()) {
		var ret int32
		return ret
	}
	return *o.CurrentPlanProbeCostMicros.Get()
}

// GetCurrentPlanProbeCostMicrosOk returns a tuple with the CurrentPlanProbeCostMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientUsageResponse) GetCurrentPlanProbeCostMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentPlanProbeCostMicros.Get(), o.CurrentPlanProbeCostMicros.IsSet()
}

// HasCurrentPlanProbeCostMicros returns a boolean if a field has been set.
func (o *ClientUsageResponse) HasCurrentPlanProbeCostMicros() bool {
	if o != nil && o.CurrentPlanProbeCostMicros.IsSet() {
		return true
	}

	return false
}

// SetCurrentPlanProbeCostMicros gets a reference to the given NullableInt32 and assigns it to the CurrentPlanProbeCostMicros field.
func (o *ClientUsageResponse) SetCurrentPlanProbeCostMicros(v int32) {
	o.CurrentPlanProbeCostMicros.Set(&v)
}
// SetCurrentPlanProbeCostMicrosNil sets the value for CurrentPlanProbeCostMicros to be an explicit nil
func (o *ClientUsageResponse) SetCurrentPlanProbeCostMicrosNil() {
	o.CurrentPlanProbeCostMicros.Set(nil)
}

// UnsetCurrentPlanProbeCostMicros ensures that no value is present for CurrentPlanProbeCostMicros, not even an explicit nil
func (o *ClientUsageResponse) UnsetCurrentPlanProbeCostMicros() {
	o.CurrentPlanProbeCostMicros.Unset()
}

func (o ClientUsageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientUsageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plan_tier"] = o.PlanTier
	toSerialize["billing_mode"] = o.BillingMode
	if o.BillingStatus.IsSet() {
		toSerialize["billing_status"] = o.BillingStatus.Get()
	}
	toSerialize["free_window_limit"] = o.FreeWindowLimit
	toSerialize["free_window_hours"] = o.FreeWindowHours
	toSerialize["free_weekly_limit"] = o.FreeWeeklyLimit
	toSerialize["window_requests_used"] = o.WindowRequestsUsed
	toSerialize["weekly_requests_used"] = o.WeeklyRequestsUsed
	toSerialize["window_requests_remaining"] = o.WindowRequestsRemaining
	toSerialize["weekly_requests_remaining"] = o.WeeklyRequestsRemaining
	if o.BillingCycleValueMicros.IsSet() {
		toSerialize["billing_cycle_value_micros"] = o.BillingCycleValueMicros.Get()
	}
	toSerialize["billing_extra_value_micros"] = o.BillingExtraValueMicros
	toSerialize["billing_value_micros_used"] = o.BillingValueMicrosUsed
	if !IsNil(o.BillingValueMicrosReserved) {
		toSerialize["billing_value_micros_reserved"] = o.BillingValueMicrosReserved
	}
	if o.BillingValueMicrosRemaining.IsSet() {
		toSerialize["billing_value_micros_remaining"] = o.BillingValueMicrosRemaining.Get()
	}
	if o.UsagePercentRemaining.IsSet() {
		toSerialize["usage_percent_remaining"] = o.UsagePercentRemaining.Get()
	}
	if o.CurrentPlanFinderDeliverableCostMicros.IsSet() {
		toSerialize["current_plan_finder_deliverable_cost_micros"] = o.CurrentPlanFinderDeliverableCostMicros.Get()
	}
	if o.CurrentPlanFinderUndeliverableCostMicros.IsSet() {
		toSerialize["current_plan_finder_undeliverable_cost_micros"] = o.CurrentPlanFinderUndeliverableCostMicros.Get()
	}
	if o.CurrentPlanProbeCostMicros.IsSet() {
		toSerialize["current_plan_probe_cost_micros"] = o.CurrentPlanProbeCostMicros.Get()
	}
	return toSerialize, nil
}

func (o *ClientUsageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plan_tier",
		"billing_mode",
		"free_window_limit",
		"free_window_hours",
		"free_weekly_limit",
		"window_requests_used",
		"weekly_requests_used",
		"window_requests_remaining",
		"weekly_requests_remaining",
		"billing_extra_value_micros",
		"billing_value_micros_used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientUsageResponse := _ClientUsageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClientUsageResponse)

	if err != nil {
		return err
	}

	*o = ClientUsageResponse(varClientUsageResponse)

	return err
}

type NullableClientUsageResponse struct {
	value *ClientUsageResponse
	isSet bool
}

func (v NullableClientUsageResponse) Get() *ClientUsageResponse {
	return v.value
}

func (v *NullableClientUsageResponse) Set(val *ClientUsageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientUsageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientUsageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientUsageResponse(val *ClientUsageResponse) *NullableClientUsageResponse {
	return &NullableClientUsageResponse{value: val, isSet: true}
}

func (v NullableClientUsageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientUsageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


