/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FinderBatchJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FinderBatchJobRequest{}

// FinderBatchJobRequest Queue a background Finder workload that can wait for capacity and complete asynchronously.
type FinderBatchJobRequest struct {
	// Optional hard deadline for the job. Omit it to start as soon as capacity allows. If provided, the API returns 422 when the deadline is too tight even with immediate execution.
	Deadline *time.Time `json:"deadline,omitempty"`
	CallbackUrl NullableString `json:"callback_url,omitempty"`
	// One or more Finder-style inputs that will be processed asynchronously.
	Inputs []FinderBatchJobRequestInputsInner `json:"inputs"`
}

type _FinderBatchJobRequest FinderBatchJobRequest

// NewFinderBatchJobRequest instantiates a new FinderBatchJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinderBatchJobRequest(inputs []FinderBatchJobRequestInputsInner) *FinderBatchJobRequest {
	this := FinderBatchJobRequest{}
	this.Inputs = inputs
	return &this
}

// NewFinderBatchJobRequestWithDefaults instantiates a new FinderBatchJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinderBatchJobRequestWithDefaults() *FinderBatchJobRequest {
	this := FinderBatchJobRequest{}
	return &this
}

// GetDeadline returns the Deadline field value if set, zero value otherwise.
func (o *FinderBatchJobRequest) GetDeadline() time.Time {
	if o == nil || IsNil(o.Deadline) {
		var ret time.Time
		return ret
	}
	return *o.Deadline
}

// GetDeadlineOk returns a tuple with the Deadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinderBatchJobRequest) GetDeadlineOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Deadline) {
		return nil, false
	}
	return o.Deadline, true
}

// HasDeadline returns a boolean if a field has been set.
func (o *FinderBatchJobRequest) HasDeadline() bool {
	if o != nil && !IsNil(o.Deadline) {
		return true
	}

	return false
}

// SetDeadline gets a reference to the given time.Time and assigns it to the Deadline field.
func (o *FinderBatchJobRequest) SetDeadline(v time.Time) {
	o.Deadline = &v
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FinderBatchJobRequest) GetCallbackUrl() string {
	if o == nil || IsNil(o.CallbackUrl.Get()) {
		var ret string
		return ret
	}
	return *o.CallbackUrl.Get()
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FinderBatchJobRequest) GetCallbackUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CallbackUrl.Get(), o.CallbackUrl.IsSet()
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *FinderBatchJobRequest) HasCallbackUrl() bool {
	if o != nil && o.CallbackUrl.IsSet() {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given NullableString and assigns it to the CallbackUrl field.
func (o *FinderBatchJobRequest) SetCallbackUrl(v string) {
	o.CallbackUrl.Set(&v)
}
// SetCallbackUrlNil sets the value for CallbackUrl to be an explicit nil
func (o *FinderBatchJobRequest) SetCallbackUrlNil() {
	o.CallbackUrl.Set(nil)
}

// UnsetCallbackUrl ensures that no value is present for CallbackUrl, not even an explicit nil
func (o *FinderBatchJobRequest) UnsetCallbackUrl() {
	o.CallbackUrl.Unset()
}

// GetInputs returns the Inputs field value
func (o *FinderBatchJobRequest) GetInputs() []FinderBatchJobRequestInputsInner {
	if o == nil {
		var ret []FinderBatchJobRequestInputsInner
		return ret
	}

	return o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value
// and a boolean to check if the value has been set.
func (o *FinderBatchJobRequest) GetInputsOk() ([]FinderBatchJobRequestInputsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Inputs, true
}

// SetInputs sets field value
func (o *FinderBatchJobRequest) SetInputs(v []FinderBatchJobRequestInputsInner) {
	o.Inputs = v
}

func (o FinderBatchJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FinderBatchJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deadline) {
		toSerialize["deadline"] = o.Deadline
	}
	if o.CallbackUrl.IsSet() {
		toSerialize["callback_url"] = o.CallbackUrl.Get()
	}
	toSerialize["inputs"] = o.Inputs
	return toSerialize, nil
}

func (o *FinderBatchJobRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"inputs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFinderBatchJobRequest := _FinderBatchJobRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFinderBatchJobRequest)

	if err != nil {
		return err
	}

	*o = FinderBatchJobRequest(varFinderBatchJobRequest)

	return err
}

type NullableFinderBatchJobRequest struct {
	value *FinderBatchJobRequest
	isSet bool
}

func (v NullableFinderBatchJobRequest) Get() *FinderBatchJobRequest {
	return v.value
}

func (v *NullableFinderBatchJobRequest) Set(val *FinderBatchJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFinderBatchJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFinderBatchJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinderBatchJobRequest(val *FinderBatchJobRequest) *NullableFinderBatchJobRequest {
	return &NullableFinderBatchJobRequest{value: val, isSet: true}
}

func (v NullableFinderBatchJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinderBatchJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


