/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchSummary{}

// BatchSummary struct for BatchSummary
type BatchSummary struct {
	// Total number of requested items.
	Total int32 `json:"total"`
	// Items that resolved to a positive deliverable result.
	Found int32 `json:"found"`
	// Items that completed cleanly with a negative result.
	NotFound int32 `json:"not_found"`
	// Items that ended with an operational verification error rather than a mailbox verdict.
	Errors int32 `json:"errors"`
	// Distinct mailbox domains represented in the batch.
	UniqueDomains int32 `json:"unique_domains"`
}

type _BatchSummary BatchSummary

// NewBatchSummary instantiates a new BatchSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchSummary(total int32, found int32, notFound int32, errors int32, uniqueDomains int32) *BatchSummary {
	this := BatchSummary{}
	this.Total = total
	this.Found = found
	this.NotFound = notFound
	this.Errors = errors
	this.UniqueDomains = uniqueDomains
	return &this
}

// NewBatchSummaryWithDefaults instantiates a new BatchSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchSummaryWithDefaults() *BatchSummary {
	this := BatchSummary{}
	return &this
}

// GetTotal returns the Total field value
func (o *BatchSummary) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *BatchSummary) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *BatchSummary) SetTotal(v int32) {
	o.Total = v
}

// GetFound returns the Found field value
func (o *BatchSummary) GetFound() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Found
}

// GetFoundOk returns a tuple with the Found field value
// and a boolean to check if the value has been set.
func (o *BatchSummary) GetFoundOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Found, true
}

// SetFound sets field value
func (o *BatchSummary) SetFound(v int32) {
	o.Found = v
}

// GetNotFound returns the NotFound field value
func (o *BatchSummary) GetNotFound() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NotFound
}

// GetNotFoundOk returns a tuple with the NotFound field value
// and a boolean to check if the value has been set.
func (o *BatchSummary) GetNotFoundOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotFound, true
}

// SetNotFound sets field value
func (o *BatchSummary) SetNotFound(v int32) {
	o.NotFound = v
}

// GetErrors returns the Errors field value
func (o *BatchSummary) GetErrors() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value
// and a boolean to check if the value has been set.
func (o *BatchSummary) GetErrorsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Errors, true
}

// SetErrors sets field value
func (o *BatchSummary) SetErrors(v int32) {
	o.Errors = v
}

// GetUniqueDomains returns the UniqueDomains field value
func (o *BatchSummary) GetUniqueDomains() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UniqueDomains
}

// GetUniqueDomainsOk returns a tuple with the UniqueDomains field value
// and a boolean to check if the value has been set.
func (o *BatchSummary) GetUniqueDomainsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UniqueDomains, true
}

// SetUniqueDomains sets field value
func (o *BatchSummary) SetUniqueDomains(v int32) {
	o.UniqueDomains = v
}

func (o BatchSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["found"] = o.Found
	toSerialize["not_found"] = o.NotFound
	toSerialize["errors"] = o.Errors
	toSerialize["unique_domains"] = o.UniqueDomains
	return toSerialize, nil
}

func (o *BatchSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"found",
		"not_found",
		"errors",
		"unique_domains",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchSummary := _BatchSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchSummary)

	if err != nil {
		return err
	}

	*o = BatchSummary(varBatchSummary)

	return err
}

type NullableBatchSummary struct {
	value *BatchSummary
	isSet bool
}

func (v NullableBatchSummary) Get() *BatchSummary {
	return v.value
}

func (v *NullableBatchSummary) Set(val *BatchSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchSummary(val *BatchSummary) *NullableBatchSummary {
	return &NullableBatchSummary{value: val, isSet: true}
}

func (v NullableBatchSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


