/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClientFinderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientFinderResponse{}

// ClientFinderResponse Compact public result envelope used by Finder and Probe style responses.
type ClientFinderResponse struct {
	// Final public deliverability verdict.
	State string `json:"state"`
	// Operational outcome. `error` means the verification could not complete cleanly and should not be treated as a negative mailbox verdict.
	Outcome *string `json:"outcome,omitempty"`
	Address NullableString `json:"address,omitempty"`
	// Whether the resolved address is an alias rather than a primary mailbox.
	IsAlias *bool `json:"is_alias,omitempty"`
	Alias *ClientFinderResponseAlias `json:"alias,omitempty"`
	// Whether the mailbox domain behaved like a catch-all during verification.
	IsCatchall *bool `json:"is_catchall,omitempty"`
	// Identity providers associated with the mailbox domain when available.
	IdentityProviders []IdentityProvider `json:"identity_providers,omitempty"`
	// Observed MX hosts for the mailbox domain.
	MxHosts []string `json:"mx_hosts,omitempty"`
	RequestId NullableString `json:"request_id,omitempty"`
}

type _ClientFinderResponse ClientFinderResponse

// NewClientFinderResponse instantiates a new ClientFinderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientFinderResponse(state string) *ClientFinderResponse {
	this := ClientFinderResponse{}
	this.State = state
	return &this
}

// NewClientFinderResponseWithDefaults instantiates a new ClientFinderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientFinderResponseWithDefaults() *ClientFinderResponse {
	this := ClientFinderResponse{}
	return &this
}

// GetState returns the State field value
func (o *ClientFinderResponse) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ClientFinderResponse) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ClientFinderResponse) SetState(v string) {
	o.State = v
}

// GetOutcome returns the Outcome field value if set, zero value otherwise.
func (o *ClientFinderResponse) GetOutcome() string {
	if o == nil || IsNil(o.Outcome) {
		var ret string
		return ret
	}
	return *o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFinderResponse) GetOutcomeOk() (*string, bool) {
	if o == nil || IsNil(o.Outcome) {
		return nil, false
	}
	return o.Outcome, true
}

// HasOutcome returns a boolean if a field has been set.
func (o *ClientFinderResponse) HasOutcome() bool {
	if o != nil && !IsNil(o.Outcome) {
		return true
	}

	return false
}

// SetOutcome gets a reference to the given string and assigns it to the Outcome field.
func (o *ClientFinderResponse) SetOutcome(v string) {
	o.Outcome = &v
}

// GetAddress returns the Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientFinderResponse) GetAddress() string {
	if o == nil || IsNil(o.Address.Get()) {
		var ret string
		return ret
	}
	return *o.Address.Get()
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientFinderResponse) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address.Get(), o.Address.IsSet()
}

// HasAddress returns a boolean if a field has been set.
func (o *ClientFinderResponse) HasAddress() bool {
	if o != nil && o.Address.IsSet() {
		return true
	}

	return false
}

// SetAddress gets a reference to the given NullableString and assigns it to the Address field.
func (o *ClientFinderResponse) SetAddress(v string) {
	o.Address.Set(&v)
}
// SetAddressNil sets the value for Address to be an explicit nil
func (o *ClientFinderResponse) SetAddressNil() {
	o.Address.Set(nil)
}

// UnsetAddress ensures that no value is present for Address, not even an explicit nil
func (o *ClientFinderResponse) UnsetAddress() {
	o.Address.Unset()
}

// GetIsAlias returns the IsAlias field value if set, zero value otherwise.
func (o *ClientFinderResponse) GetIsAlias() bool {
	if o == nil || IsNil(o.IsAlias) {
		var ret bool
		return ret
	}
	return *o.IsAlias
}

// GetIsAliasOk returns a tuple with the IsAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFinderResponse) GetIsAliasOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAlias) {
		return nil, false
	}
	return o.IsAlias, true
}

// HasIsAlias returns a boolean if a field has been set.
func (o *ClientFinderResponse) HasIsAlias() bool {
	if o != nil && !IsNil(o.IsAlias) {
		return true
	}

	return false
}

// SetIsAlias gets a reference to the given bool and assigns it to the IsAlias field.
func (o *ClientFinderResponse) SetIsAlias(v bool) {
	o.IsAlias = &v
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *ClientFinderResponse) GetAlias() ClientFinderResponseAlias {
	if o == nil || IsNil(o.Alias) {
		var ret ClientFinderResponseAlias
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFinderResponse) GetAliasOk() (*ClientFinderResponseAlias, bool) {
	if o == nil || IsNil(o.Alias) {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *ClientFinderResponse) HasAlias() bool {
	if o != nil && !IsNil(o.Alias) {
		return true
	}

	return false
}

// SetAlias gets a reference to the given ClientFinderResponseAlias and assigns it to the Alias field.
func (o *ClientFinderResponse) SetAlias(v ClientFinderResponseAlias) {
	o.Alias = &v
}

// GetIsCatchall returns the IsCatchall field value if set, zero value otherwise.
func (o *ClientFinderResponse) GetIsCatchall() bool {
	if o == nil || IsNil(o.IsCatchall) {
		var ret bool
		return ret
	}
	return *o.IsCatchall
}

// GetIsCatchallOk returns a tuple with the IsCatchall field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFinderResponse) GetIsCatchallOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCatchall) {
		return nil, false
	}
	return o.IsCatchall, true
}

// HasIsCatchall returns a boolean if a field has been set.
func (o *ClientFinderResponse) HasIsCatchall() bool {
	if o != nil && !IsNil(o.IsCatchall) {
		return true
	}

	return false
}

// SetIsCatchall gets a reference to the given bool and assigns it to the IsCatchall field.
func (o *ClientFinderResponse) SetIsCatchall(v bool) {
	o.IsCatchall = &v
}

// GetIdentityProviders returns the IdentityProviders field value if set, zero value otherwise.
func (o *ClientFinderResponse) GetIdentityProviders() []IdentityProvider {
	if o == nil || IsNil(o.IdentityProviders) {
		var ret []IdentityProvider
		return ret
	}
	return o.IdentityProviders
}

// GetIdentityProvidersOk returns a tuple with the IdentityProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFinderResponse) GetIdentityProvidersOk() ([]IdentityProvider, bool) {
	if o == nil || IsNil(o.IdentityProviders) {
		return nil, false
	}
	return o.IdentityProviders, true
}

// HasIdentityProviders returns a boolean if a field has been set.
func (o *ClientFinderResponse) HasIdentityProviders() bool {
	if o != nil && !IsNil(o.IdentityProviders) {
		return true
	}

	return false
}

// SetIdentityProviders gets a reference to the given []IdentityProvider and assigns it to the IdentityProviders field.
func (o *ClientFinderResponse) SetIdentityProviders(v []IdentityProvider) {
	o.IdentityProviders = v
}

// GetMxHosts returns the MxHosts field value if set, zero value otherwise.
func (o *ClientFinderResponse) GetMxHosts() []string {
	if o == nil || IsNil(o.MxHosts) {
		var ret []string
		return ret
	}
	return o.MxHosts
}

// GetMxHostsOk returns a tuple with the MxHosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFinderResponse) GetMxHostsOk() ([]string, bool) {
	if o == nil || IsNil(o.MxHosts) {
		return nil, false
	}
	return o.MxHosts, true
}

// HasMxHosts returns a boolean if a field has been set.
func (o *ClientFinderResponse) HasMxHosts() bool {
	if o != nil && !IsNil(o.MxHosts) {
		return true
	}

	return false
}

// SetMxHosts gets a reference to the given []string and assigns it to the MxHosts field.
func (o *ClientFinderResponse) SetMxHosts(v []string) {
	o.MxHosts = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientFinderResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId.Get()) {
		var ret string
		return ret
	}
	return *o.RequestId.Get()
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientFinderResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestId.Get(), o.RequestId.IsSet()
}

// HasRequestId returns a boolean if a field has been set.
func (o *ClientFinderResponse) HasRequestId() bool {
	if o != nil && o.RequestId.IsSet() {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given NullableString and assigns it to the RequestId field.
func (o *ClientFinderResponse) SetRequestId(v string) {
	o.RequestId.Set(&v)
}
// SetRequestIdNil sets the value for RequestId to be an explicit nil
func (o *ClientFinderResponse) SetRequestIdNil() {
	o.RequestId.Set(nil)
}

// UnsetRequestId ensures that no value is present for RequestId, not even an explicit nil
func (o *ClientFinderResponse) UnsetRequestId() {
	o.RequestId.Unset()
}

func (o ClientFinderResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientFinderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	if !IsNil(o.Outcome) {
		toSerialize["outcome"] = o.Outcome
	}
	if o.Address.IsSet() {
		toSerialize["address"] = o.Address.Get()
	}
	if !IsNil(o.IsAlias) {
		toSerialize["is_alias"] = o.IsAlias
	}
	if !IsNil(o.Alias) {
		toSerialize["alias"] = o.Alias
	}
	if !IsNil(o.IsCatchall) {
		toSerialize["is_catchall"] = o.IsCatchall
	}
	if !IsNil(o.IdentityProviders) {
		toSerialize["identity_providers"] = o.IdentityProviders
	}
	if !IsNil(o.MxHosts) {
		toSerialize["mx_hosts"] = o.MxHosts
	}
	if o.RequestId.IsSet() {
		toSerialize["request_id"] = o.RequestId.Get()
	}
	return toSerialize, nil
}

func (o *ClientFinderResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientFinderResponse := _ClientFinderResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClientFinderResponse)

	if err != nil {
		return err
	}

	*o = ClientFinderResponse(varClientFinderResponse)

	return err
}

type NullableClientFinderResponse struct {
	value *ClientFinderResponse
	isSet bool
}

func (v NullableClientFinderResponse) Get() *ClientFinderResponse {
	return v.value
}

func (v *NullableClientFinderResponse) Set(val *ClientFinderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientFinderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientFinderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientFinderResponse(val *ClientFinderResponse) *NullableClientFinderResponse {
	return &NullableClientFinderResponse{value: val, isSet: true}
}

func (v NullableClientFinderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientFinderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


