/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProbeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProbeRequest{}

// ProbeRequest Verify one known email address directly.
type ProbeRequest struct {
	// The email address you want to verify.
	Email string `json:"email"`
}

type _ProbeRequest ProbeRequest

// NewProbeRequest instantiates a new ProbeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProbeRequest(email string) *ProbeRequest {
	this := ProbeRequest{}
	this.Email = email
	return &this
}

// NewProbeRequestWithDefaults instantiates a new ProbeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProbeRequestWithDefaults() *ProbeRequest {
	this := ProbeRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *ProbeRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ProbeRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ProbeRequest) SetEmail(v string) {
	o.Email = v
}

func (o ProbeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProbeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *ProbeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProbeRequest := _ProbeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProbeRequest)

	if err != nil {
		return err
	}

	*o = ProbeRequest(varProbeRequest)

	return err
}

type NullableProbeRequest struct {
	value *ProbeRequest
	isSet bool
}

func (v NullableProbeRequest) Get() *ProbeRequest {
	return v.value
}

func (v *NullableProbeRequest) Set(val *ProbeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProbeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProbeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProbeRequest(val *ProbeRequest) *NullableProbeRequest {
	return &NullableProbeRequest{value: val, isSet: true}
}

func (v NullableProbeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProbeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


