/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
)

// checks if the AliasInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AliasInfo{}

// AliasInfo Alias information when email is resolved to a different address.
type AliasInfo struct {
	Original NullableString `json:"original,omitempty"`
	Resolved NullableString `json:"resolved,omitempty"`
}

// NewAliasInfo instantiates a new AliasInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAliasInfo() *AliasInfo {
	this := AliasInfo{}
	return &this
}

// NewAliasInfoWithDefaults instantiates a new AliasInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAliasInfoWithDefaults() *AliasInfo {
	this := AliasInfo{}
	return &this
}

// GetOriginal returns the Original field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AliasInfo) GetOriginal() string {
	if o == nil || IsNil(o.Original.Get()) {
		var ret string
		return ret
	}
	return *o.Original.Get()
}

// GetOriginalOk returns a tuple with the Original field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AliasInfo) GetOriginalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Original.Get(), o.Original.IsSet()
}

// HasOriginal returns a boolean if a field has been set.
func (o *AliasInfo) HasOriginal() bool {
	if o != nil && o.Original.IsSet() {
		return true
	}

	return false
}

// SetOriginal gets a reference to the given NullableString and assigns it to the Original field.
func (o *AliasInfo) SetOriginal(v string) {
	o.Original.Set(&v)
}
// SetOriginalNil sets the value for Original to be an explicit nil
func (o *AliasInfo) SetOriginalNil() {
	o.Original.Set(nil)
}

// UnsetOriginal ensures that no value is present for Original, not even an explicit nil
func (o *AliasInfo) UnsetOriginal() {
	o.Original.Unset()
}

// GetResolved returns the Resolved field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AliasInfo) GetResolved() string {
	if o == nil || IsNil(o.Resolved.Get()) {
		var ret string
		return ret
	}
	return *o.Resolved.Get()
}

// GetResolvedOk returns a tuple with the Resolved field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AliasInfo) GetResolvedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Resolved.Get(), o.Resolved.IsSet()
}

// HasResolved returns a boolean if a field has been set.
func (o *AliasInfo) HasResolved() bool {
	if o != nil && o.Resolved.IsSet() {
		return true
	}

	return false
}

// SetResolved gets a reference to the given NullableString and assigns it to the Resolved field.
func (o *AliasInfo) SetResolved(v string) {
	o.Resolved.Set(&v)
}
// SetResolvedNil sets the value for Resolved to be an explicit nil
func (o *AliasInfo) SetResolvedNil() {
	o.Resolved.Set(nil)
}

// UnsetResolved ensures that no value is present for Resolved, not even an explicit nil
func (o *AliasInfo) UnsetResolved() {
	o.Resolved.Unset()
}

func (o AliasInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AliasInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Original.IsSet() {
		toSerialize["original"] = o.Original.Get()
	}
	if o.Resolved.IsSet() {
		toSerialize["resolved"] = o.Resolved.Get()
	}
	return toSerialize, nil
}

type NullableAliasInfo struct {
	value *AliasInfo
	isSet bool
}

func (v NullableAliasInfo) Get() *AliasInfo {
	return v.value
}

func (v *NullableAliasInfo) Set(val *AliasInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAliasInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAliasInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAliasInfo(val *AliasInfo) *NullableAliasInfo {
	return &NullableAliasInfo{value: val, isSet: true}
}

func (v NullableAliasInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAliasInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


