/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ClientTokenStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientTokenStatusResponse{}

// ClientTokenStatusResponse Current bearer token claims as seen by the API.
type ClientTokenStatusResponse struct {
	// Whether the current bearer token is valid for this request.
	Valid *bool `json:"valid,omitempty"`
	// User id associated with the bearer token.
	UserId string `json:"user_id"`
	// How the bearer token was issued.
	TokenType string `json:"token_type"`
	// Scopes currently attached to the bearer token.
	Scopes []string `json:"scopes,omitempty"`
	ExpiresAt NullableTime `json:"expires_at,omitempty"`
	ExpiresInSeconds NullableInt32 `json:"expires_in_seconds,omitempty"`
}

type _ClientTokenStatusResponse ClientTokenStatusResponse

// NewClientTokenStatusResponse instantiates a new ClientTokenStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientTokenStatusResponse(userId string, tokenType string) *ClientTokenStatusResponse {
	this := ClientTokenStatusResponse{}
	this.UserId = userId
	this.TokenType = tokenType
	return &this
}

// NewClientTokenStatusResponseWithDefaults instantiates a new ClientTokenStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientTokenStatusResponseWithDefaults() *ClientTokenStatusResponse {
	this := ClientTokenStatusResponse{}
	return &this
}

// GetValid returns the Valid field value if set, zero value otherwise.
func (o *ClientTokenStatusResponse) GetValid() bool {
	if o == nil || IsNil(o.Valid) {
		var ret bool
		return ret
	}
	return *o.Valid
}

// GetValidOk returns a tuple with the Valid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientTokenStatusResponse) GetValidOk() (*bool, bool) {
	if o == nil || IsNil(o.Valid) {
		return nil, false
	}
	return o.Valid, true
}

// HasValid returns a boolean if a field has been set.
func (o *ClientTokenStatusResponse) HasValid() bool {
	if o != nil && !IsNil(o.Valid) {
		return true
	}

	return false
}

// SetValid gets a reference to the given bool and assigns it to the Valid field.
func (o *ClientTokenStatusResponse) SetValid(v bool) {
	o.Valid = &v
}

// GetUserId returns the UserId field value
func (o *ClientTokenStatusResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ClientTokenStatusResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ClientTokenStatusResponse) SetUserId(v string) {
	o.UserId = v
}

// GetTokenType returns the TokenType field value
func (o *ClientTokenStatusResponse) GetTokenType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value
// and a boolean to check if the value has been set.
func (o *ClientTokenStatusResponse) GetTokenTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenType, true
}

// SetTokenType sets field value
func (o *ClientTokenStatusResponse) SetTokenType(v string) {
	o.TokenType = v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *ClientTokenStatusResponse) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientTokenStatusResponse) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *ClientTokenStatusResponse) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *ClientTokenStatusResponse) SetScopes(v []string) {
	o.Scopes = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientTokenStatusResponse) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientTokenStatusResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *ClientTokenStatusResponse) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *ClientTokenStatusResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *ClientTokenStatusResponse) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *ClientTokenStatusResponse) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetExpiresInSeconds returns the ExpiresInSeconds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientTokenStatusResponse) GetExpiresInSeconds() int32 {
	if o == nil || IsNil(o.ExpiresInSeconds.Get()) {
		var ret int32
		return ret
	}
	return *o.ExpiresInSeconds.Get()
}

// GetExpiresInSecondsOk returns a tuple with the ExpiresInSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientTokenStatusResponse) GetExpiresInSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresInSeconds.Get(), o.ExpiresInSeconds.IsSet()
}

// HasExpiresInSeconds returns a boolean if a field has been set.
func (o *ClientTokenStatusResponse) HasExpiresInSeconds() bool {
	if o != nil && o.ExpiresInSeconds.IsSet() {
		return true
	}

	return false
}

// SetExpiresInSeconds gets a reference to the given NullableInt32 and assigns it to the ExpiresInSeconds field.
func (o *ClientTokenStatusResponse) SetExpiresInSeconds(v int32) {
	o.ExpiresInSeconds.Set(&v)
}
// SetExpiresInSecondsNil sets the value for ExpiresInSeconds to be an explicit nil
func (o *ClientTokenStatusResponse) SetExpiresInSecondsNil() {
	o.ExpiresInSeconds.Set(nil)
}

// UnsetExpiresInSeconds ensures that no value is present for ExpiresInSeconds, not even an explicit nil
func (o *ClientTokenStatusResponse) UnsetExpiresInSeconds() {
	o.ExpiresInSeconds.Unset()
}

func (o ClientTokenStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientTokenStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Valid) {
		toSerialize["valid"] = o.Valid
	}
	toSerialize["user_id"] = o.UserId
	toSerialize["token_type"] = o.TokenType
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	if o.ExpiresInSeconds.IsSet() {
		toSerialize["expires_in_seconds"] = o.ExpiresInSeconds.Get()
	}
	return toSerialize, nil
}

func (o *ClientTokenStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
		"token_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientTokenStatusResponse := _ClientTokenStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClientTokenStatusResponse)

	if err != nil {
		return err
	}

	*o = ClientTokenStatusResponse(varClientTokenStatusResponse)

	return err
}

type NullableClientTokenStatusResponse struct {
	value *ClientTokenStatusResponse
	isSet bool
}

func (v NullableClientTokenStatusResponse) Get() *ClientTokenStatusResponse {
	return v.value
}

func (v *NullableClientTokenStatusResponse) Set(val *ClientTokenStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientTokenStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientTokenStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientTokenStatusResponse(val *ClientTokenStatusResponse) *NullableClientTokenStatusResponse {
	return &NullableClientTokenStatusResponse{value: val, isSet: true}
}

func (v NullableClientTokenStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientTokenStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


