/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FinderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FinderRequest{}

// FinderRequest Resolve the most likely verified work email for one person at one company domain.
type FinderRequest struct {
	// The real person's full name. Include middle names or initials when known.
	FullName string `json:"full_name"`
	// The company's public website or mailbox domain.
	EmailDomain string `json:"email_domain"`
}

type _FinderRequest FinderRequest

// NewFinderRequest instantiates a new FinderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinderRequest(fullName string, emailDomain string) *FinderRequest {
	this := FinderRequest{}
	this.FullName = fullName
	this.EmailDomain = emailDomain
	return &this
}

// NewFinderRequestWithDefaults instantiates a new FinderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinderRequestWithDefaults() *FinderRequest {
	this := FinderRequest{}
	return &this
}

// GetFullName returns the FullName field value
func (o *FinderRequest) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *FinderRequest) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *FinderRequest) SetFullName(v string) {
	o.FullName = v
}

// GetEmailDomain returns the EmailDomain field value
func (o *FinderRequest) GetEmailDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmailDomain
}

// GetEmailDomainOk returns a tuple with the EmailDomain field value
// and a boolean to check if the value has been set.
func (o *FinderRequest) GetEmailDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmailDomain, true
}

// SetEmailDomain sets field value
func (o *FinderRequest) SetEmailDomain(v string) {
	o.EmailDomain = v
}

func (o FinderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FinderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["full_name"] = o.FullName
	toSerialize["email_domain"] = o.EmailDomain
	return toSerialize, nil
}

func (o *FinderRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"full_name",
		"email_domain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFinderRequest := _FinderRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFinderRequest)

	if err != nil {
		return err
	}

	*o = FinderRequest(varFinderRequest)

	return err
}

type NullableFinderRequest struct {
	value *FinderRequest
	isSet bool
}

func (v NullableFinderRequest) Get() *FinderRequest {
	return v.value
}

func (v *NullableFinderRequest) Set(val *FinderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFinderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFinderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinderRequest(val *FinderRequest) *NullableFinderRequest {
	return &NullableFinderRequest{value: val, isSet: true}
}

func (v NullableFinderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


