/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProbeBatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProbeBatchRequest{}

// ProbeBatchRequest Verify many known email addresses synchronously and receive compact per-item results.
type ProbeBatchRequest struct {
	// One or more exact mailbox addresses to verify.
	Emails []string `json:"emails"`
}

type _ProbeBatchRequest ProbeBatchRequest

// NewProbeBatchRequest instantiates a new ProbeBatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProbeBatchRequest(emails []string) *ProbeBatchRequest {
	this := ProbeBatchRequest{}
	this.Emails = emails
	return &this
}

// NewProbeBatchRequestWithDefaults instantiates a new ProbeBatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProbeBatchRequestWithDefaults() *ProbeBatchRequest {
	this := ProbeBatchRequest{}
	return &this
}

// GetEmails returns the Emails field value
func (o *ProbeBatchRequest) GetEmails() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value
// and a boolean to check if the value has been set.
func (o *ProbeBatchRequest) GetEmailsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Emails, true
}

// SetEmails sets field value
func (o *ProbeBatchRequest) SetEmails(v []string) {
	o.Emails = v
}

func (o ProbeBatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProbeBatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["emails"] = o.Emails
	return toSerialize, nil
}

func (o *ProbeBatchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"emails",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProbeBatchRequest := _ProbeBatchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProbeBatchRequest)

	if err != nil {
		return err
	}

	*o = ProbeBatchRequest(varProbeBatchRequest)

	return err
}

type NullableProbeBatchRequest struct {
	value *ProbeBatchRequest
	isSet bool
}

func (v NullableProbeBatchRequest) Get() *ProbeBatchRequest {
	return v.value
}

func (v *NullableProbeBatchRequest) Set(val *ProbeBatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProbeBatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProbeBatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProbeBatchRequest(val *ProbeBatchRequest) *NullableProbeBatchRequest {
	return &NullableProbeBatchRequest{value: val, isSet: true}
}

func (v NullableProbeBatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProbeBatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


