/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClientBackgroundJobDetailResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientBackgroundJobDetailResponse{}

// ClientBackgroundJobDetailResponse Background job detail plus paginated item results.
type ClientBackgroundJobDetailResponse struct {
	Job ClientBackgroundJobResponse `json:"job"`
	Items []ClientBackgroundJobItemResponse `json:"items"`
	TotalItems int32 `json:"total_items"`
	Page int32 `json:"page"`
	PageSize int32 `json:"page_size"`
	TotalPages int32 `json:"total_pages"`
	// Whether the stored item payload rows have already expired and been pruned.
	ResultsExpired *bool `json:"results_expired,omitempty"`
}

type _ClientBackgroundJobDetailResponse ClientBackgroundJobDetailResponse

// NewClientBackgroundJobDetailResponse instantiates a new ClientBackgroundJobDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientBackgroundJobDetailResponse(job ClientBackgroundJobResponse, items []ClientBackgroundJobItemResponse, totalItems int32, page int32, pageSize int32, totalPages int32) *ClientBackgroundJobDetailResponse {
	this := ClientBackgroundJobDetailResponse{}
	this.Job = job
	this.Items = items
	this.TotalItems = totalItems
	this.Page = page
	this.PageSize = pageSize
	this.TotalPages = totalPages
	return &this
}

// NewClientBackgroundJobDetailResponseWithDefaults instantiates a new ClientBackgroundJobDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientBackgroundJobDetailResponseWithDefaults() *ClientBackgroundJobDetailResponse {
	this := ClientBackgroundJobDetailResponse{}
	return &this
}

// GetJob returns the Job field value
func (o *ClientBackgroundJobDetailResponse) GetJob() ClientBackgroundJobResponse {
	if o == nil {
		var ret ClientBackgroundJobResponse
		return ret
	}

	return o.Job
}

// GetJobOk returns a tuple with the Job field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobDetailResponse) GetJobOk() (*ClientBackgroundJobResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Job, true
}

// SetJob sets field value
func (o *ClientBackgroundJobDetailResponse) SetJob(v ClientBackgroundJobResponse) {
	o.Job = v
}

// GetItems returns the Items field value
func (o *ClientBackgroundJobDetailResponse) GetItems() []ClientBackgroundJobItemResponse {
	if o == nil {
		var ret []ClientBackgroundJobItemResponse
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobDetailResponse) GetItemsOk() ([]ClientBackgroundJobItemResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ClientBackgroundJobDetailResponse) SetItems(v []ClientBackgroundJobItemResponse) {
	o.Items = v
}

// GetTotalItems returns the TotalItems field value
func (o *ClientBackgroundJobDetailResponse) GetTotalItems() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalItems
}

// GetTotalItemsOk returns a tuple with the TotalItems field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobDetailResponse) GetTotalItemsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalItems, true
}

// SetTotalItems sets field value
func (o *ClientBackgroundJobDetailResponse) SetTotalItems(v int32) {
	o.TotalItems = v
}

// GetPage returns the Page field value
func (o *ClientBackgroundJobDetailResponse) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobDetailResponse) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *ClientBackgroundJobDetailResponse) SetPage(v int32) {
	o.Page = v
}

// GetPageSize returns the PageSize field value
func (o *ClientBackgroundJobDetailResponse) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobDetailResponse) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *ClientBackgroundJobDetailResponse) SetPageSize(v int32) {
	o.PageSize = v
}

// GetTotalPages returns the TotalPages field value
func (o *ClientBackgroundJobDetailResponse) GetTotalPages() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobDetailResponse) GetTotalPagesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPages, true
}

// SetTotalPages sets field value
func (o *ClientBackgroundJobDetailResponse) SetTotalPages(v int32) {
	o.TotalPages = v
}

// GetResultsExpired returns the ResultsExpired field value if set, zero value otherwise.
func (o *ClientBackgroundJobDetailResponse) GetResultsExpired() bool {
	if o == nil || IsNil(o.ResultsExpired) {
		var ret bool
		return ret
	}
	return *o.ResultsExpired
}

// GetResultsExpiredOk returns a tuple with the ResultsExpired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobDetailResponse) GetResultsExpiredOk() (*bool, bool) {
	if o == nil || IsNil(o.ResultsExpired) {
		return nil, false
	}
	return o.ResultsExpired, true
}

// HasResultsExpired returns a boolean if a field has been set.
func (o *ClientBackgroundJobDetailResponse) HasResultsExpired() bool {
	if o != nil && !IsNil(o.ResultsExpired) {
		return true
	}

	return false
}

// SetResultsExpired gets a reference to the given bool and assigns it to the ResultsExpired field.
func (o *ClientBackgroundJobDetailResponse) SetResultsExpired(v bool) {
	o.ResultsExpired = &v
}

func (o ClientBackgroundJobDetailResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientBackgroundJobDetailResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job"] = o.Job
	toSerialize["items"] = o.Items
	toSerialize["total_items"] = o.TotalItems
	toSerialize["page"] = o.Page
	toSerialize["page_size"] = o.PageSize
	toSerialize["total_pages"] = o.TotalPages
	if !IsNil(o.ResultsExpired) {
		toSerialize["results_expired"] = o.ResultsExpired
	}
	return toSerialize, nil
}

func (o *ClientBackgroundJobDetailResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job",
		"items",
		"total_items",
		"page",
		"page_size",
		"total_pages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientBackgroundJobDetailResponse := _ClientBackgroundJobDetailResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClientBackgroundJobDetailResponse)

	if err != nil {
		return err
	}

	*o = ClientBackgroundJobDetailResponse(varClientBackgroundJobDetailResponse)

	return err
}

type NullableClientBackgroundJobDetailResponse struct {
	value *ClientBackgroundJobDetailResponse
	isSet bool
}

func (v NullableClientBackgroundJobDetailResponse) Get() *ClientBackgroundJobDetailResponse {
	return v.value
}

func (v *NullableClientBackgroundJobDetailResponse) Set(val *ClientBackgroundJobDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientBackgroundJobDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientBackgroundJobDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientBackgroundJobDetailResponse(val *ClientBackgroundJobDetailResponse) *NullableClientBackgroundJobDetailResponse {
	return &NullableClientBackgroundJobDetailResponse{value: val, isSet: true}
}

func (v NullableClientBackgroundJobDetailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientBackgroundJobDetailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


