/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClientRequestHistoryPageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientRequestHistoryPageResponse{}

// ClientRequestHistoryPageResponse Paginated request history result.
type ClientRequestHistoryPageResponse struct {
	Items []ClientRequestHistoryItem `json:"items"`
	Total int32 `json:"total"`
	Page int32 `json:"page"`
	PageSize int32 `json:"page_size"`
	TotalPages int32 `json:"total_pages"`
}

type _ClientRequestHistoryPageResponse ClientRequestHistoryPageResponse

// NewClientRequestHistoryPageResponse instantiates a new ClientRequestHistoryPageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientRequestHistoryPageResponse(items []ClientRequestHistoryItem, total int32, page int32, pageSize int32, totalPages int32) *ClientRequestHistoryPageResponse {
	this := ClientRequestHistoryPageResponse{}
	this.Items = items
	this.Total = total
	this.Page = page
	this.PageSize = pageSize
	this.TotalPages = totalPages
	return &this
}

// NewClientRequestHistoryPageResponseWithDefaults instantiates a new ClientRequestHistoryPageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientRequestHistoryPageResponseWithDefaults() *ClientRequestHistoryPageResponse {
	this := ClientRequestHistoryPageResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *ClientRequestHistoryPageResponse) GetItems() []ClientRequestHistoryItem {
	if o == nil {
		var ret []ClientRequestHistoryItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryPageResponse) GetItemsOk() ([]ClientRequestHistoryItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ClientRequestHistoryPageResponse) SetItems(v []ClientRequestHistoryItem) {
	o.Items = v
}

// GetTotal returns the Total field value
func (o *ClientRequestHistoryPageResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryPageResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ClientRequestHistoryPageResponse) SetTotal(v int32) {
	o.Total = v
}

// GetPage returns the Page field value
func (o *ClientRequestHistoryPageResponse) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryPageResponse) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *ClientRequestHistoryPageResponse) SetPage(v int32) {
	o.Page = v
}

// GetPageSize returns the PageSize field value
func (o *ClientRequestHistoryPageResponse) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryPageResponse) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *ClientRequestHistoryPageResponse) SetPageSize(v int32) {
	o.PageSize = v
}

// GetTotalPages returns the TotalPages field value
func (o *ClientRequestHistoryPageResponse) GetTotalPages() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryPageResponse) GetTotalPagesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPages, true
}

// SetTotalPages sets field value
func (o *ClientRequestHistoryPageResponse) SetTotalPages(v int32) {
	o.TotalPages = v
}

func (o ClientRequestHistoryPageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientRequestHistoryPageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["total"] = o.Total
	toSerialize["page"] = o.Page
	toSerialize["page_size"] = o.PageSize
	toSerialize["total_pages"] = o.TotalPages
	return toSerialize, nil
}

func (o *ClientRequestHistoryPageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"total",
		"page",
		"page_size",
		"total_pages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientRequestHistoryPageResponse := _ClientRequestHistoryPageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClientRequestHistoryPageResponse)

	if err != nil {
		return err
	}

	*o = ClientRequestHistoryPageResponse(varClientRequestHistoryPageResponse)

	return err
}

type NullableClientRequestHistoryPageResponse struct {
	value *ClientRequestHistoryPageResponse
	isSet bool
}

func (v NullableClientRequestHistoryPageResponse) Get() *ClientRequestHistoryPageResponse {
	return v.value
}

func (v *NullableClientRequestHistoryPageResponse) Set(val *ClientRequestHistoryPageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientRequestHistoryPageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientRequestHistoryPageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientRequestHistoryPageResponse(val *ClientRequestHistoryPageResponse) *NullableClientRequestHistoryPageResponse {
	return &NullableClientRequestHistoryPageResponse{value: val, isSet: true}
}

func (v NullableClientRequestHistoryPageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientRequestHistoryPageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


