/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ClientBackgroundJobResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientBackgroundJobResponse{}

// ClientBackgroundJobResponse Background job status envelope returned by the public jobs API.
type ClientBackgroundJobResponse struct {
	Id string `json:"id"`
	JobType string `json:"job_type"`
	// Current high-level job lifecycle state.
	Status string `json:"status"`
	DeadlineAt time.Time `json:"deadline_at"`
	EstimatedRuntimeSeconds int32 `json:"estimated_runtime_seconds"`
	ScheduledStartAt time.Time `json:"scheduled_start_at"`
	CallbackUrl NullableString `json:"callback_url,omitempty"`
	CallbackStatus string `json:"callback_status"`
	CallbackAttempts int32 `json:"callback_attempts"`
	CallbackLastError NullableString `json:"callback_last_error,omitempty"`
	// Total number of submitted items for the job.
	RequestedCount int32 `json:"requested_count"`
	CompletedCount int32 `json:"completed_count"`
	SuccessCount int32 `json:"success_count"`
	NotFoundCount int32 `json:"not_found_count"`
	ErrorCount int32 `json:"error_count"`
	ReservedAmountMicros int32 `json:"reserved_amount_micros"`
	ActualAmountMicros int32 `json:"actual_amount_micros"`
	// Approximate percent complete based on completed item count.
	ProgressPercent *float32 `json:"progress_percent,omitempty"`
	// Aggregated counts and provider stats for the job.
	Summary map[string]interface{} `json:"summary,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	StartedAt NullableTime `json:"started_at,omitempty"`
	CompletedAt NullableTime `json:"completed_at,omitempty"`
	HistoryExpiresAt NullableTime `json:"history_expires_at,omitempty"`
	ResultsPrunedAt NullableTime `json:"results_pruned_at,omitempty"`
	ArtifactAvailable *bool `json:"artifact_available,omitempty"`
	ArtifactJsonUrl NullableString `json:"artifact_json_url,omitempty"`
	ArtifactSizeBytes NullableInt32 `json:"artifact_size_bytes,omitempty"`
	ArtifactUploadedAt NullableTime `json:"artifact_uploaded_at,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type _ClientBackgroundJobResponse ClientBackgroundJobResponse

// NewClientBackgroundJobResponse instantiates a new ClientBackgroundJobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientBackgroundJobResponse(id string, jobType string, status string, deadlineAt time.Time, estimatedRuntimeSeconds int32, scheduledStartAt time.Time, callbackStatus string, callbackAttempts int32, requestedCount int32, completedCount int32, successCount int32, notFoundCount int32, errorCount int32, reservedAmountMicros int32, actualAmountMicros int32, createdAt time.Time, updatedAt time.Time) *ClientBackgroundJobResponse {
	this := ClientBackgroundJobResponse{}
	this.Id = id
	this.JobType = jobType
	this.Status = status
	this.DeadlineAt = deadlineAt
	this.EstimatedRuntimeSeconds = estimatedRuntimeSeconds
	this.ScheduledStartAt = scheduledStartAt
	this.CallbackStatus = callbackStatus
	this.CallbackAttempts = callbackAttempts
	this.RequestedCount = requestedCount
	this.CompletedCount = completedCount
	this.SuccessCount = successCount
	this.NotFoundCount = notFoundCount
	this.ErrorCount = errorCount
	this.ReservedAmountMicros = reservedAmountMicros
	this.ActualAmountMicros = actualAmountMicros
	var artifactAvailable bool = false
	this.ArtifactAvailable = &artifactAvailable
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewClientBackgroundJobResponseWithDefaults instantiates a new ClientBackgroundJobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientBackgroundJobResponseWithDefaults() *ClientBackgroundJobResponse {
	this := ClientBackgroundJobResponse{}
	var artifactAvailable bool = false
	this.ArtifactAvailable = &artifactAvailable
	return &this
}

// GetId returns the Id field value
func (o *ClientBackgroundJobResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ClientBackgroundJobResponse) SetId(v string) {
	o.Id = v
}

// GetJobType returns the JobType field value
func (o *ClientBackgroundJobResponse) GetJobType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobType
}

// GetJobTypeOk returns a tuple with the JobType field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetJobTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobType, true
}

// SetJobType sets field value
func (o *ClientBackgroundJobResponse) SetJobType(v string) {
	o.JobType = v
}

// GetStatus returns the Status field value
func (o *ClientBackgroundJobResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ClientBackgroundJobResponse) SetStatus(v string) {
	o.Status = v
}

// GetDeadlineAt returns the DeadlineAt field value
func (o *ClientBackgroundJobResponse) GetDeadlineAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.DeadlineAt
}

// GetDeadlineAtOk returns a tuple with the DeadlineAt field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetDeadlineAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeadlineAt, true
}

// SetDeadlineAt sets field value
func (o *ClientBackgroundJobResponse) SetDeadlineAt(v time.Time) {
	o.DeadlineAt = v
}

// GetEstimatedRuntimeSeconds returns the EstimatedRuntimeSeconds field value
func (o *ClientBackgroundJobResponse) GetEstimatedRuntimeSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EstimatedRuntimeSeconds
}

// GetEstimatedRuntimeSecondsOk returns a tuple with the EstimatedRuntimeSeconds field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetEstimatedRuntimeSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EstimatedRuntimeSeconds, true
}

// SetEstimatedRuntimeSeconds sets field value
func (o *ClientBackgroundJobResponse) SetEstimatedRuntimeSeconds(v int32) {
	o.EstimatedRuntimeSeconds = v
}

// GetScheduledStartAt returns the ScheduledStartAt field value
func (o *ClientBackgroundJobResponse) GetScheduledStartAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ScheduledStartAt
}

// GetScheduledStartAtOk returns a tuple with the ScheduledStartAt field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetScheduledStartAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduledStartAt, true
}

// SetScheduledStartAt sets field value
func (o *ClientBackgroundJobResponse) SetScheduledStartAt(v time.Time) {
	o.ScheduledStartAt = v
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobResponse) GetCallbackUrl() string {
	if o == nil || IsNil(o.CallbackUrl.Get()) {
		var ret string
		return ret
	}
	return *o.CallbackUrl.Get()
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobResponse) GetCallbackUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CallbackUrl.Get(), o.CallbackUrl.IsSet()
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *ClientBackgroundJobResponse) HasCallbackUrl() bool {
	if o != nil && o.CallbackUrl.IsSet() {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given NullableString and assigns it to the CallbackUrl field.
func (o *ClientBackgroundJobResponse) SetCallbackUrl(v string) {
	o.CallbackUrl.Set(&v)
}
// SetCallbackUrlNil sets the value for CallbackUrl to be an explicit nil
func (o *ClientBackgroundJobResponse) SetCallbackUrlNil() {
	o.CallbackUrl.Set(nil)
}

// UnsetCallbackUrl ensures that no value is present for CallbackUrl, not even an explicit nil
func (o *ClientBackgroundJobResponse) UnsetCallbackUrl() {
	o.CallbackUrl.Unset()
}

// GetCallbackStatus returns the CallbackStatus field value
func (o *ClientBackgroundJobResponse) GetCallbackStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CallbackStatus
}

// GetCallbackStatusOk returns a tuple with the CallbackStatus field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetCallbackStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallbackStatus, true
}

// SetCallbackStatus sets field value
func (o *ClientBackgroundJobResponse) SetCallbackStatus(v string) {
	o.CallbackStatus = v
}

// GetCallbackAttempts returns the CallbackAttempts field value
func (o *ClientBackgroundJobResponse) GetCallbackAttempts() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CallbackAttempts
}

// GetCallbackAttemptsOk returns a tuple with the CallbackAttempts field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetCallbackAttemptsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallbackAttempts, true
}

// SetCallbackAttempts sets field value
func (o *ClientBackgroundJobResponse) SetCallbackAttempts(v int32) {
	o.CallbackAttempts = v
}

// GetCallbackLastError returns the CallbackLastError field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobResponse) GetCallbackLastError() string {
	if o == nil || IsNil(o.CallbackLastError.Get()) {
		var ret string
		return ret
	}
	return *o.CallbackLastError.Get()
}

// GetCallbackLastErrorOk returns a tuple with the CallbackLastError field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobResponse) GetCallbackLastErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CallbackLastError.Get(), o.CallbackLastError.IsSet()
}

// HasCallbackLastError returns a boolean if a field has been set.
func (o *ClientBackgroundJobResponse) HasCallbackLastError() bool {
	if o != nil && o.CallbackLastError.IsSet() {
		return true
	}

	return false
}

// SetCallbackLastError gets a reference to the given NullableString and assigns it to the CallbackLastError field.
func (o *ClientBackgroundJobResponse) SetCallbackLastError(v string) {
	o.CallbackLastError.Set(&v)
}
// SetCallbackLastErrorNil sets the value for CallbackLastError to be an explicit nil
func (o *ClientBackgroundJobResponse) SetCallbackLastErrorNil() {
	o.CallbackLastError.Set(nil)
}

// UnsetCallbackLastError ensures that no value is present for CallbackLastError, not even an explicit nil
func (o *ClientBackgroundJobResponse) UnsetCallbackLastError() {
	o.CallbackLastError.Unset()
}

// GetRequestedCount returns the RequestedCount field value
func (o *ClientBackgroundJobResponse) GetRequestedCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RequestedCount
}

// GetRequestedCountOk returns a tuple with the RequestedCount field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetRequestedCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestedCount, true
}

// SetRequestedCount sets field value
func (o *ClientBackgroundJobResponse) SetRequestedCount(v int32) {
	o.RequestedCount = v
}

// GetCompletedCount returns the CompletedCount field value
func (o *ClientBackgroundJobResponse) GetCompletedCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CompletedCount
}

// GetCompletedCountOk returns a tuple with the CompletedCount field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetCompletedCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompletedCount, true
}

// SetCompletedCount sets field value
func (o *ClientBackgroundJobResponse) SetCompletedCount(v int32) {
	o.CompletedCount = v
}

// GetSuccessCount returns the SuccessCount field value
func (o *ClientBackgroundJobResponse) GetSuccessCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SuccessCount
}

// GetSuccessCountOk returns a tuple with the SuccessCount field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetSuccessCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuccessCount, true
}

// SetSuccessCount sets field value
func (o *ClientBackgroundJobResponse) SetSuccessCount(v int32) {
	o.SuccessCount = v
}

// GetNotFoundCount returns the NotFoundCount field value
func (o *ClientBackgroundJobResponse) GetNotFoundCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NotFoundCount
}

// GetNotFoundCountOk returns a tuple with the NotFoundCount field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetNotFoundCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotFoundCount, true
}

// SetNotFoundCount sets field value
func (o *ClientBackgroundJobResponse) SetNotFoundCount(v int32) {
	o.NotFoundCount = v
}

// GetErrorCount returns the ErrorCount field value
func (o *ClientBackgroundJobResponse) GetErrorCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ErrorCount
}

// GetErrorCountOk returns a tuple with the ErrorCount field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetErrorCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorCount, true
}

// SetErrorCount sets field value
func (o *ClientBackgroundJobResponse) SetErrorCount(v int32) {
	o.ErrorCount = v
}

// GetReservedAmountMicros returns the ReservedAmountMicros field value
func (o *ClientBackgroundJobResponse) GetReservedAmountMicros() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReservedAmountMicros
}

// GetReservedAmountMicrosOk returns a tuple with the ReservedAmountMicros field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetReservedAmountMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReservedAmountMicros, true
}

// SetReservedAmountMicros sets field value
func (o *ClientBackgroundJobResponse) SetReservedAmountMicros(v int32) {
	o.ReservedAmountMicros = v
}

// GetActualAmountMicros returns the ActualAmountMicros field value
func (o *ClientBackgroundJobResponse) GetActualAmountMicros() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActualAmountMicros
}

// GetActualAmountMicrosOk returns a tuple with the ActualAmountMicros field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetActualAmountMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActualAmountMicros, true
}

// SetActualAmountMicros sets field value
func (o *ClientBackgroundJobResponse) SetActualAmountMicros(v int32) {
	o.ActualAmountMicros = v
}

// GetProgressPercent returns the ProgressPercent field value if set, zero value otherwise.
func (o *ClientBackgroundJobResponse) GetProgressPercent() float32 {
	if o == nil || IsNil(o.ProgressPercent) {
		var ret float32
		return ret
	}
	return *o.ProgressPercent
}

// GetProgressPercentOk returns a tuple with the ProgressPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetProgressPercentOk() (*float32, bool) {
	if o == nil || IsNil(o.ProgressPercent) {
		return nil, false
	}
	return o.ProgressPercent, true
}

// HasProgressPercent returns a boolean if a field has been set.
func (o *ClientBackgroundJobResponse) HasProgressPercent() bool {
	if o != nil && !IsNil(o.ProgressPercent) {
		return true
	}

	return false
}

// SetProgressPercent gets a reference to the given float32 and assigns it to the ProgressPercent field.
func (o *ClientBackgroundJobResponse) SetProgressPercent(v float32) {
	o.ProgressPercent = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *ClientBackgroundJobResponse) GetSummary() map[string]interface{} {
	if o == nil || IsNil(o.Summary) {
		var ret map[string]interface{}
		return ret
	}
	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetSummaryOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Summary) {
		return map[string]interface{}{}, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *ClientBackgroundJobResponse) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given map[string]interface{} and assigns it to the Summary field.
func (o *ClientBackgroundJobResponse) SetSummary(v map[string]interface{}) {
	o.Summary = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ClientBackgroundJobResponse) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ClientBackgroundJobResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *ClientBackgroundJobResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobResponse) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobResponse) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *ClientBackgroundJobResponse) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableTime and assigns it to the StartedAt field.
func (o *ClientBackgroundJobResponse) SetStartedAt(v time.Time) {
	o.StartedAt.Set(&v)
}
// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *ClientBackgroundJobResponse) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *ClientBackgroundJobResponse) UnsetStartedAt() {
	o.StartedAt.Unset()
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobResponse) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobResponse) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *ClientBackgroundJobResponse) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableTime and assigns it to the CompletedAt field.
func (o *ClientBackgroundJobResponse) SetCompletedAt(v time.Time) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *ClientBackgroundJobResponse) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *ClientBackgroundJobResponse) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetHistoryExpiresAt returns the HistoryExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobResponse) GetHistoryExpiresAt() time.Time {
	if o == nil || IsNil(o.HistoryExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.HistoryExpiresAt.Get()
}

// GetHistoryExpiresAtOk returns a tuple with the HistoryExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobResponse) GetHistoryExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.HistoryExpiresAt.Get(), o.HistoryExpiresAt.IsSet()
}

// HasHistoryExpiresAt returns a boolean if a field has been set.
func (o *ClientBackgroundJobResponse) HasHistoryExpiresAt() bool {
	if o != nil && o.HistoryExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetHistoryExpiresAt gets a reference to the given NullableTime and assigns it to the HistoryExpiresAt field.
func (o *ClientBackgroundJobResponse) SetHistoryExpiresAt(v time.Time) {
	o.HistoryExpiresAt.Set(&v)
}
// SetHistoryExpiresAtNil sets the value for HistoryExpiresAt to be an explicit nil
func (o *ClientBackgroundJobResponse) SetHistoryExpiresAtNil() {
	o.HistoryExpiresAt.Set(nil)
}

// UnsetHistoryExpiresAt ensures that no value is present for HistoryExpiresAt, not even an explicit nil
func (o *ClientBackgroundJobResponse) UnsetHistoryExpiresAt() {
	o.HistoryExpiresAt.Unset()
}

// GetResultsPrunedAt returns the ResultsPrunedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobResponse) GetResultsPrunedAt() time.Time {
	if o == nil || IsNil(o.ResultsPrunedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ResultsPrunedAt.Get()
}

// GetResultsPrunedAtOk returns a tuple with the ResultsPrunedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobResponse) GetResultsPrunedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultsPrunedAt.Get(), o.ResultsPrunedAt.IsSet()
}

// HasResultsPrunedAt returns a boolean if a field has been set.
func (o *ClientBackgroundJobResponse) HasResultsPrunedAt() bool {
	if o != nil && o.ResultsPrunedAt.IsSet() {
		return true
	}

	return false
}

// SetResultsPrunedAt gets a reference to the given NullableTime and assigns it to the ResultsPrunedAt field.
func (o *ClientBackgroundJobResponse) SetResultsPrunedAt(v time.Time) {
	o.ResultsPrunedAt.Set(&v)
}
// SetResultsPrunedAtNil sets the value for ResultsPrunedAt to be an explicit nil
func (o *ClientBackgroundJobResponse) SetResultsPrunedAtNil() {
	o.ResultsPrunedAt.Set(nil)
}

// UnsetResultsPrunedAt ensures that no value is present for ResultsPrunedAt, not even an explicit nil
func (o *ClientBackgroundJobResponse) UnsetResultsPrunedAt() {
	o.ResultsPrunedAt.Unset()
}

// GetArtifactAvailable returns the ArtifactAvailable field value if set, zero value otherwise.
func (o *ClientBackgroundJobResponse) GetArtifactAvailable() bool {
	if o == nil || IsNil(o.ArtifactAvailable) {
		var ret bool
		return ret
	}
	return *o.ArtifactAvailable
}

// GetArtifactAvailableOk returns a tuple with the ArtifactAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetArtifactAvailableOk() (*bool, bool) {
	if o == nil || IsNil(o.ArtifactAvailable) {
		return nil, false
	}
	return o.ArtifactAvailable, true
}

// HasArtifactAvailable returns a boolean if a field has been set.
func (o *ClientBackgroundJobResponse) HasArtifactAvailable() bool {
	if o != nil && !IsNil(o.ArtifactAvailable) {
		return true
	}

	return false
}

// SetArtifactAvailable gets a reference to the given bool and assigns it to the ArtifactAvailable field.
func (o *ClientBackgroundJobResponse) SetArtifactAvailable(v bool) {
	o.ArtifactAvailable = &v
}

// GetArtifactJsonUrl returns the ArtifactJsonUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobResponse) GetArtifactJsonUrl() string {
	if o == nil || IsNil(o.ArtifactJsonUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ArtifactJsonUrl.Get()
}

// GetArtifactJsonUrlOk returns a tuple with the ArtifactJsonUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobResponse) GetArtifactJsonUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArtifactJsonUrl.Get(), o.ArtifactJsonUrl.IsSet()
}

// HasArtifactJsonUrl returns a boolean if a field has been set.
func (o *ClientBackgroundJobResponse) HasArtifactJsonUrl() bool {
	if o != nil && o.ArtifactJsonUrl.IsSet() {
		return true
	}

	return false
}

// SetArtifactJsonUrl gets a reference to the given NullableString and assigns it to the ArtifactJsonUrl field.
func (o *ClientBackgroundJobResponse) SetArtifactJsonUrl(v string) {
	o.ArtifactJsonUrl.Set(&v)
}
// SetArtifactJsonUrlNil sets the value for ArtifactJsonUrl to be an explicit nil
func (o *ClientBackgroundJobResponse) SetArtifactJsonUrlNil() {
	o.ArtifactJsonUrl.Set(nil)
}

// UnsetArtifactJsonUrl ensures that no value is present for ArtifactJsonUrl, not even an explicit nil
func (o *ClientBackgroundJobResponse) UnsetArtifactJsonUrl() {
	o.ArtifactJsonUrl.Unset()
}

// GetArtifactSizeBytes returns the ArtifactSizeBytes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobResponse) GetArtifactSizeBytes() int32 {
	if o == nil || IsNil(o.ArtifactSizeBytes.Get()) {
		var ret int32
		return ret
	}
	return *o.ArtifactSizeBytes.Get()
}

// GetArtifactSizeBytesOk returns a tuple with the ArtifactSizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobResponse) GetArtifactSizeBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArtifactSizeBytes.Get(), o.ArtifactSizeBytes.IsSet()
}

// HasArtifactSizeBytes returns a boolean if a field has been set.
func (o *ClientBackgroundJobResponse) HasArtifactSizeBytes() bool {
	if o != nil && o.ArtifactSizeBytes.IsSet() {
		return true
	}

	return false
}

// SetArtifactSizeBytes gets a reference to the given NullableInt32 and assigns it to the ArtifactSizeBytes field.
func (o *ClientBackgroundJobResponse) SetArtifactSizeBytes(v int32) {
	o.ArtifactSizeBytes.Set(&v)
}
// SetArtifactSizeBytesNil sets the value for ArtifactSizeBytes to be an explicit nil
func (o *ClientBackgroundJobResponse) SetArtifactSizeBytesNil() {
	o.ArtifactSizeBytes.Set(nil)
}

// UnsetArtifactSizeBytes ensures that no value is present for ArtifactSizeBytes, not even an explicit nil
func (o *ClientBackgroundJobResponse) UnsetArtifactSizeBytes() {
	o.ArtifactSizeBytes.Unset()
}

// GetArtifactUploadedAt returns the ArtifactUploadedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobResponse) GetArtifactUploadedAt() time.Time {
	if o == nil || IsNil(o.ArtifactUploadedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ArtifactUploadedAt.Get()
}

// GetArtifactUploadedAtOk returns a tuple with the ArtifactUploadedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobResponse) GetArtifactUploadedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArtifactUploadedAt.Get(), o.ArtifactUploadedAt.IsSet()
}

// HasArtifactUploadedAt returns a boolean if a field has been set.
func (o *ClientBackgroundJobResponse) HasArtifactUploadedAt() bool {
	if o != nil && o.ArtifactUploadedAt.IsSet() {
		return true
	}

	return false
}

// SetArtifactUploadedAt gets a reference to the given NullableTime and assigns it to the ArtifactUploadedAt field.
func (o *ClientBackgroundJobResponse) SetArtifactUploadedAt(v time.Time) {
	o.ArtifactUploadedAt.Set(&v)
}
// SetArtifactUploadedAtNil sets the value for ArtifactUploadedAt to be an explicit nil
func (o *ClientBackgroundJobResponse) SetArtifactUploadedAtNil() {
	o.ArtifactUploadedAt.Set(nil)
}

// UnsetArtifactUploadedAt ensures that no value is present for ArtifactUploadedAt, not even an explicit nil
func (o *ClientBackgroundJobResponse) UnsetArtifactUploadedAt() {
	o.ArtifactUploadedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *ClientBackgroundJobResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ClientBackgroundJobResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ClientBackgroundJobResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ClientBackgroundJobResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o ClientBackgroundJobResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientBackgroundJobResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["job_type"] = o.JobType
	toSerialize["status"] = o.Status
	toSerialize["deadline_at"] = o.DeadlineAt
	toSerialize["estimated_runtime_seconds"] = o.EstimatedRuntimeSeconds
	toSerialize["scheduled_start_at"] = o.ScheduledStartAt
	if o.CallbackUrl.IsSet() {
		toSerialize["callback_url"] = o.CallbackUrl.Get()
	}
	toSerialize["callback_status"] = o.CallbackStatus
	toSerialize["callback_attempts"] = o.CallbackAttempts
	if o.CallbackLastError.IsSet() {
		toSerialize["callback_last_error"] = o.CallbackLastError.Get()
	}
	toSerialize["requested_count"] = o.RequestedCount
	toSerialize["completed_count"] = o.CompletedCount
	toSerialize["success_count"] = o.SuccessCount
	toSerialize["not_found_count"] = o.NotFoundCount
	toSerialize["error_count"] = o.ErrorCount
	toSerialize["reserved_amount_micros"] = o.ReservedAmountMicros
	toSerialize["actual_amount_micros"] = o.ActualAmountMicros
	if !IsNil(o.ProgressPercent) {
		toSerialize["progress_percent"] = o.ProgressPercent
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if o.StartedAt.IsSet() {
		toSerialize["started_at"] = o.StartedAt.Get()
	}
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	if o.HistoryExpiresAt.IsSet() {
		toSerialize["history_expires_at"] = o.HistoryExpiresAt.Get()
	}
	if o.ResultsPrunedAt.IsSet() {
		toSerialize["results_pruned_at"] = o.ResultsPrunedAt.Get()
	}
	if !IsNil(o.ArtifactAvailable) {
		toSerialize["artifact_available"] = o.ArtifactAvailable
	}
	if o.ArtifactJsonUrl.IsSet() {
		toSerialize["artifact_json_url"] = o.ArtifactJsonUrl.Get()
	}
	if o.ArtifactSizeBytes.IsSet() {
		toSerialize["artifact_size_bytes"] = o.ArtifactSizeBytes.Get()
	}
	if o.ArtifactUploadedAt.IsSet() {
		toSerialize["artifact_uploaded_at"] = o.ArtifactUploadedAt.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *ClientBackgroundJobResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"job_type",
		"status",
		"deadline_at",
		"estimated_runtime_seconds",
		"scheduled_start_at",
		"callback_status",
		"callback_attempts",
		"requested_count",
		"completed_count",
		"success_count",
		"not_found_count",
		"error_count",
		"reserved_amount_micros",
		"actual_amount_micros",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientBackgroundJobResponse := _ClientBackgroundJobResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClientBackgroundJobResponse)

	if err != nil {
		return err
	}

	*o = ClientBackgroundJobResponse(varClientBackgroundJobResponse)

	return err
}

type NullableClientBackgroundJobResponse struct {
	value *ClientBackgroundJobResponse
	isSet bool
}

func (v NullableClientBackgroundJobResponse) Get() *ClientBackgroundJobResponse {
	return v.value
}

func (v *NullableClientBackgroundJobResponse) Set(val *ClientBackgroundJobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientBackgroundJobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientBackgroundJobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientBackgroundJobResponse(val *ClientBackgroundJobResponse) *NullableClientBackgroundJobResponse {
	return &NullableClientBackgroundJobResponse{value: val, isSet: true}
}

func (v NullableClientBackgroundJobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientBackgroundJobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


