/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"fmt"
)


// ClientFinderResponseAlias Alias metadata when `is_alias=true`.
type ClientFinderResponseAlias struct {
	AliasInfo *AliasInfo
	MapmapOfStringAny *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ClientFinderResponseAlias) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AliasInfo
	err = json.Unmarshal(data, &dst.AliasInfo);
	if err == nil {
		jsonAliasInfo, _ := json.Marshal(dst.AliasInfo)
		if string(jsonAliasInfo) == "{}" { // empty struct
			dst.AliasInfo = nil
		} else {
			return nil // data stored in dst.AliasInfo, return on the first match
		}
	} else {
		dst.AliasInfo = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny);
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ClientFinderResponseAlias)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ClientFinderResponseAlias) MarshalJSON() ([]byte, error) {
	if src.AliasInfo != nil {
		return json.Marshal(&src.AliasInfo)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableClientFinderResponseAlias struct {
	value *ClientFinderResponseAlias
	isSet bool
}

func (v NullableClientFinderResponseAlias) Get() *ClientFinderResponseAlias {
	return v.value
}

func (v *NullableClientFinderResponseAlias) Set(val *ClientFinderResponseAlias) {
	v.value = val
	v.isSet = true
}

func (v NullableClientFinderResponseAlias) IsSet() bool {
	return v.isSet
}

func (v *NullableClientFinderResponseAlias) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientFinderResponseAlias(val *ClientFinderResponseAlias) *NullableClientFinderResponseAlias {
	return &NullableClientFinderResponseAlias{value: val, isSet: true}
}

func (v NullableClientFinderResponseAlias) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientFinderResponseAlias) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


