/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ClientBackgroundJobItemResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientBackgroundJobItemResponse{}

// ClientBackgroundJobItemResponse One item inside a background job payload.
type ClientBackgroundJobItemResponse struct {
	Id string `json:"id"`
	ItemIndex int32 `json:"item_index"`
	Status string `json:"status"`
	RequestType string `json:"request_type"`
	// Original submitted input for this item.
	Input map[string]interface{} `json:"input"`
	Result map[string]interface{} `json:"result,omitempty"`
	ResultState NullableString `json:"result_state,omitempty"`
	ResultOutcome NullableString `json:"result_outcome,omitempty"`
	ResolvedAddress NullableString `json:"resolved_address,omitempty"`
	Provider NullableString `json:"provider,omitempty"`
	ChargeMicros *int32 `json:"charge_micros,omitempty"`
	ErrorMessage NullableString `json:"error_message,omitempty"`
	StartedAt NullableTime `json:"started_at,omitempty"`
	CompletedAt NullableTime `json:"completed_at,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type _ClientBackgroundJobItemResponse ClientBackgroundJobItemResponse

// NewClientBackgroundJobItemResponse instantiates a new ClientBackgroundJobItemResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientBackgroundJobItemResponse(id string, itemIndex int32, status string, requestType string, input map[string]interface{}, createdAt time.Time, updatedAt time.Time) *ClientBackgroundJobItemResponse {
	this := ClientBackgroundJobItemResponse{}
	this.Id = id
	this.ItemIndex = itemIndex
	this.Status = status
	this.RequestType = requestType
	this.Input = input
	var chargeMicros int32 = 0
	this.ChargeMicros = &chargeMicros
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewClientBackgroundJobItemResponseWithDefaults instantiates a new ClientBackgroundJobItemResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientBackgroundJobItemResponseWithDefaults() *ClientBackgroundJobItemResponse {
	this := ClientBackgroundJobItemResponse{}
	var chargeMicros int32 = 0
	this.ChargeMicros = &chargeMicros
	return &this
}

// GetId returns the Id field value
func (o *ClientBackgroundJobItemResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobItemResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ClientBackgroundJobItemResponse) SetId(v string) {
	o.Id = v
}

// GetItemIndex returns the ItemIndex field value
func (o *ClientBackgroundJobItemResponse) GetItemIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ItemIndex
}

// GetItemIndexOk returns a tuple with the ItemIndex field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobItemResponse) GetItemIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemIndex, true
}

// SetItemIndex sets field value
func (o *ClientBackgroundJobItemResponse) SetItemIndex(v int32) {
	o.ItemIndex = v
}

// GetStatus returns the Status field value
func (o *ClientBackgroundJobItemResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobItemResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ClientBackgroundJobItemResponse) SetStatus(v string) {
	o.Status = v
}

// GetRequestType returns the RequestType field value
func (o *ClientBackgroundJobItemResponse) GetRequestType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestType
}

// GetRequestTypeOk returns a tuple with the RequestType field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobItemResponse) GetRequestTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestType, true
}

// SetRequestType sets field value
func (o *ClientBackgroundJobItemResponse) SetRequestType(v string) {
	o.RequestType = v
}

// GetInput returns the Input field value
func (o *ClientBackgroundJobItemResponse) GetInput() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobItemResponse) GetInputOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Input, true
}

// SetInput sets field value
func (o *ClientBackgroundJobItemResponse) SetInput(v map[string]interface{}) {
	o.Input = v
}

// GetResult returns the Result field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobItemResponse) GetResult() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobItemResponse) GetResultOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return map[string]interface{}{}, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *ClientBackgroundJobItemResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given map[string]interface{} and assigns it to the Result field.
func (o *ClientBackgroundJobItemResponse) SetResult(v map[string]interface{}) {
	o.Result = v
}

// GetResultState returns the ResultState field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobItemResponse) GetResultState() string {
	if o == nil || IsNil(o.ResultState.Get()) {
		var ret string
		return ret
	}
	return *o.ResultState.Get()
}

// GetResultStateOk returns a tuple with the ResultState field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobItemResponse) GetResultStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultState.Get(), o.ResultState.IsSet()
}

// HasResultState returns a boolean if a field has been set.
func (o *ClientBackgroundJobItemResponse) HasResultState() bool {
	if o != nil && o.ResultState.IsSet() {
		return true
	}

	return false
}

// SetResultState gets a reference to the given NullableString and assigns it to the ResultState field.
func (o *ClientBackgroundJobItemResponse) SetResultState(v string) {
	o.ResultState.Set(&v)
}
// SetResultStateNil sets the value for ResultState to be an explicit nil
func (o *ClientBackgroundJobItemResponse) SetResultStateNil() {
	o.ResultState.Set(nil)
}

// UnsetResultState ensures that no value is present for ResultState, not even an explicit nil
func (o *ClientBackgroundJobItemResponse) UnsetResultState() {
	o.ResultState.Unset()
}

// GetResultOutcome returns the ResultOutcome field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobItemResponse) GetResultOutcome() string {
	if o == nil || IsNil(o.ResultOutcome.Get()) {
		var ret string
		return ret
	}
	return *o.ResultOutcome.Get()
}

// GetResultOutcomeOk returns a tuple with the ResultOutcome field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobItemResponse) GetResultOutcomeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultOutcome.Get(), o.ResultOutcome.IsSet()
}

// HasResultOutcome returns a boolean if a field has been set.
func (o *ClientBackgroundJobItemResponse) HasResultOutcome() bool {
	if o != nil && o.ResultOutcome.IsSet() {
		return true
	}

	return false
}

// SetResultOutcome gets a reference to the given NullableString and assigns it to the ResultOutcome field.
func (o *ClientBackgroundJobItemResponse) SetResultOutcome(v string) {
	o.ResultOutcome.Set(&v)
}
// SetResultOutcomeNil sets the value for ResultOutcome to be an explicit nil
func (o *ClientBackgroundJobItemResponse) SetResultOutcomeNil() {
	o.ResultOutcome.Set(nil)
}

// UnsetResultOutcome ensures that no value is present for ResultOutcome, not even an explicit nil
func (o *ClientBackgroundJobItemResponse) UnsetResultOutcome() {
	o.ResultOutcome.Unset()
}

// GetResolvedAddress returns the ResolvedAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobItemResponse) GetResolvedAddress() string {
	if o == nil || IsNil(o.ResolvedAddress.Get()) {
		var ret string
		return ret
	}
	return *o.ResolvedAddress.Get()
}

// GetResolvedAddressOk returns a tuple with the ResolvedAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobItemResponse) GetResolvedAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResolvedAddress.Get(), o.ResolvedAddress.IsSet()
}

// HasResolvedAddress returns a boolean if a field has been set.
func (o *ClientBackgroundJobItemResponse) HasResolvedAddress() bool {
	if o != nil && o.ResolvedAddress.IsSet() {
		return true
	}

	return false
}

// SetResolvedAddress gets a reference to the given NullableString and assigns it to the ResolvedAddress field.
func (o *ClientBackgroundJobItemResponse) SetResolvedAddress(v string) {
	o.ResolvedAddress.Set(&v)
}
// SetResolvedAddressNil sets the value for ResolvedAddress to be an explicit nil
func (o *ClientBackgroundJobItemResponse) SetResolvedAddressNil() {
	o.ResolvedAddress.Set(nil)
}

// UnsetResolvedAddress ensures that no value is present for ResolvedAddress, not even an explicit nil
func (o *ClientBackgroundJobItemResponse) UnsetResolvedAddress() {
	o.ResolvedAddress.Unset()
}

// GetProvider returns the Provider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobItemResponse) GetProvider() string {
	if o == nil || IsNil(o.Provider.Get()) {
		var ret string
		return ret
	}
	return *o.Provider.Get()
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobItemResponse) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provider.Get(), o.Provider.IsSet()
}

// HasProvider returns a boolean if a field has been set.
func (o *ClientBackgroundJobItemResponse) HasProvider() bool {
	if o != nil && o.Provider.IsSet() {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullableString and assigns it to the Provider field.
func (o *ClientBackgroundJobItemResponse) SetProvider(v string) {
	o.Provider.Set(&v)
}
// SetProviderNil sets the value for Provider to be an explicit nil
func (o *ClientBackgroundJobItemResponse) SetProviderNil() {
	o.Provider.Set(nil)
}

// UnsetProvider ensures that no value is present for Provider, not even an explicit nil
func (o *ClientBackgroundJobItemResponse) UnsetProvider() {
	o.Provider.Unset()
}

// GetChargeMicros returns the ChargeMicros field value if set, zero value otherwise.
func (o *ClientBackgroundJobItemResponse) GetChargeMicros() int32 {
	if o == nil || IsNil(o.ChargeMicros) {
		var ret int32
		return ret
	}
	return *o.ChargeMicros
}

// GetChargeMicrosOk returns a tuple with the ChargeMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobItemResponse) GetChargeMicrosOk() (*int32, bool) {
	if o == nil || IsNil(o.ChargeMicros) {
		return nil, false
	}
	return o.ChargeMicros, true
}

// HasChargeMicros returns a boolean if a field has been set.
func (o *ClientBackgroundJobItemResponse) HasChargeMicros() bool {
	if o != nil && !IsNil(o.ChargeMicros) {
		return true
	}

	return false
}

// SetChargeMicros gets a reference to the given int32 and assigns it to the ChargeMicros field.
func (o *ClientBackgroundJobItemResponse) SetChargeMicros(v int32) {
	o.ChargeMicros = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobItemResponse) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorMessage.Get()
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobItemResponse) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorMessage.Get(), o.ErrorMessage.IsSet()
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *ClientBackgroundJobItemResponse) HasErrorMessage() bool {
	if o != nil && o.ErrorMessage.IsSet() {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given NullableString and assigns it to the ErrorMessage field.
func (o *ClientBackgroundJobItemResponse) SetErrorMessage(v string) {
	o.ErrorMessage.Set(&v)
}
// SetErrorMessageNil sets the value for ErrorMessage to be an explicit nil
func (o *ClientBackgroundJobItemResponse) SetErrorMessageNil() {
	o.ErrorMessage.Set(nil)
}

// UnsetErrorMessage ensures that no value is present for ErrorMessage, not even an explicit nil
func (o *ClientBackgroundJobItemResponse) UnsetErrorMessage() {
	o.ErrorMessage.Unset()
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobItemResponse) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobItemResponse) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *ClientBackgroundJobItemResponse) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableTime and assigns it to the StartedAt field.
func (o *ClientBackgroundJobItemResponse) SetStartedAt(v time.Time) {
	o.StartedAt.Set(&v)
}
// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *ClientBackgroundJobItemResponse) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *ClientBackgroundJobItemResponse) UnsetStartedAt() {
	o.StartedAt.Unset()
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientBackgroundJobItemResponse) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientBackgroundJobItemResponse) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *ClientBackgroundJobItemResponse) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableTime and assigns it to the CompletedAt field.
func (o *ClientBackgroundJobItemResponse) SetCompletedAt(v time.Time) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *ClientBackgroundJobItemResponse) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *ClientBackgroundJobItemResponse) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *ClientBackgroundJobItemResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobItemResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ClientBackgroundJobItemResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ClientBackgroundJobItemResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ClientBackgroundJobItemResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ClientBackgroundJobItemResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o ClientBackgroundJobItemResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientBackgroundJobItemResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["item_index"] = o.ItemIndex
	toSerialize["status"] = o.Status
	toSerialize["request_type"] = o.RequestType
	toSerialize["input"] = o.Input
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	if o.ResultState.IsSet() {
		toSerialize["result_state"] = o.ResultState.Get()
	}
	if o.ResultOutcome.IsSet() {
		toSerialize["result_outcome"] = o.ResultOutcome.Get()
	}
	if o.ResolvedAddress.IsSet() {
		toSerialize["resolved_address"] = o.ResolvedAddress.Get()
	}
	if o.Provider.IsSet() {
		toSerialize["provider"] = o.Provider.Get()
	}
	if !IsNil(o.ChargeMicros) {
		toSerialize["charge_micros"] = o.ChargeMicros
	}
	if o.ErrorMessage.IsSet() {
		toSerialize["error_message"] = o.ErrorMessage.Get()
	}
	if o.StartedAt.IsSet() {
		toSerialize["started_at"] = o.StartedAt.Get()
	}
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *ClientBackgroundJobItemResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"item_index",
		"status",
		"request_type",
		"input",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientBackgroundJobItemResponse := _ClientBackgroundJobItemResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClientBackgroundJobItemResponse)

	if err != nil {
		return err
	}

	*o = ClientBackgroundJobItemResponse(varClientBackgroundJobItemResponse)

	return err
}

type NullableClientBackgroundJobItemResponse struct {
	value *ClientBackgroundJobItemResponse
	isSet bool
}

func (v NullableClientBackgroundJobItemResponse) Get() *ClientBackgroundJobItemResponse {
	return v.value
}

func (v *NullableClientBackgroundJobItemResponse) Set(val *ClientBackgroundJobItemResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientBackgroundJobItemResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientBackgroundJobItemResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientBackgroundJobItemResponse(val *ClientBackgroundJobItemResponse) *NullableClientBackgroundJobItemResponse {
	return &NullableClientBackgroundJobItemResponse{value: val, isSet: true}
}

func (v NullableClientBackgroundJobItemResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientBackgroundJobItemResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


