/*
Relentless Identity API

Public client API for Finder and Probe workflows. This spec is generated from the FastAPI app, then narrowed to the supported bearer-authenticated routes used by SDKs and the API reference.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package relentlessidentity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ClientRequestHistoryItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientRequestHistoryItem{}

// ClientRequestHistoryItem One completed direct request visible in the user's request history.
type ClientRequestHistoryItem struct {
	Id string `json:"id"`
	RequestType string `json:"request_type"`
	InputName NullableString `json:"input_name,omitempty"`
	InputDomain NullableString `json:"input_domain,omitempty"`
	InputEmail NullableString `json:"input_email,omitempty"`
	// Compact human-readable identifier for the original request input.
	InputLabel string `json:"input_label"`
	State string `json:"state"`
	Outcome string `json:"outcome"`
	ResolvedAddress NullableString `json:"resolved_address,omitempty"`
	DurationMs NullableInt32 `json:"duration_ms,omitempty"`
	Provider NullableString `json:"provider,omitempty"`
	IdentityProviders []map[string]interface{} `json:"identity_providers,omitempty"`
	MxHosts []string `json:"mx_hosts,omitempty"`
	// Small transport and outcome metadata associated with the request.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	IsAlias *bool `json:"is_alias,omitempty"`
	IsCatchall *bool `json:"is_catchall,omitempty"`
	RequestId NullableString `json:"request_id,omitempty"`
	CreatedAt time.Time `json:"created_at"`
}

type _ClientRequestHistoryItem ClientRequestHistoryItem

// NewClientRequestHistoryItem instantiates a new ClientRequestHistoryItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientRequestHistoryItem(id string, requestType string, inputLabel string, state string, outcome string, createdAt time.Time) *ClientRequestHistoryItem {
	this := ClientRequestHistoryItem{}
	this.Id = id
	this.RequestType = requestType
	this.InputLabel = inputLabel
	this.State = state
	this.Outcome = outcome
	var isAlias bool = false
	this.IsAlias = &isAlias
	var isCatchall bool = false
	this.IsCatchall = &isCatchall
	this.CreatedAt = createdAt
	return &this
}

// NewClientRequestHistoryItemWithDefaults instantiates a new ClientRequestHistoryItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientRequestHistoryItemWithDefaults() *ClientRequestHistoryItem {
	this := ClientRequestHistoryItem{}
	var isAlias bool = false
	this.IsAlias = &isAlias
	var isCatchall bool = false
	this.IsCatchall = &isCatchall
	return &this
}

// GetId returns the Id field value
func (o *ClientRequestHistoryItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ClientRequestHistoryItem) SetId(v string) {
	o.Id = v
}

// GetRequestType returns the RequestType field value
func (o *ClientRequestHistoryItem) GetRequestType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestType
}

// GetRequestTypeOk returns a tuple with the RequestType field value
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryItem) GetRequestTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestType, true
}

// SetRequestType sets field value
func (o *ClientRequestHistoryItem) SetRequestType(v string) {
	o.RequestType = v
}

// GetInputName returns the InputName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientRequestHistoryItem) GetInputName() string {
	if o == nil || IsNil(o.InputName.Get()) {
		var ret string
		return ret
	}
	return *o.InputName.Get()
}

// GetInputNameOk returns a tuple with the InputName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientRequestHistoryItem) GetInputNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InputName.Get(), o.InputName.IsSet()
}

// HasInputName returns a boolean if a field has been set.
func (o *ClientRequestHistoryItem) HasInputName() bool {
	if o != nil && o.InputName.IsSet() {
		return true
	}

	return false
}

// SetInputName gets a reference to the given NullableString and assigns it to the InputName field.
func (o *ClientRequestHistoryItem) SetInputName(v string) {
	o.InputName.Set(&v)
}
// SetInputNameNil sets the value for InputName to be an explicit nil
func (o *ClientRequestHistoryItem) SetInputNameNil() {
	o.InputName.Set(nil)
}

// UnsetInputName ensures that no value is present for InputName, not even an explicit nil
func (o *ClientRequestHistoryItem) UnsetInputName() {
	o.InputName.Unset()
}

// GetInputDomain returns the InputDomain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientRequestHistoryItem) GetInputDomain() string {
	if o == nil || IsNil(o.InputDomain.Get()) {
		var ret string
		return ret
	}
	return *o.InputDomain.Get()
}

// GetInputDomainOk returns a tuple with the InputDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientRequestHistoryItem) GetInputDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InputDomain.Get(), o.InputDomain.IsSet()
}

// HasInputDomain returns a boolean if a field has been set.
func (o *ClientRequestHistoryItem) HasInputDomain() bool {
	if o != nil && o.InputDomain.IsSet() {
		return true
	}

	return false
}

// SetInputDomain gets a reference to the given NullableString and assigns it to the InputDomain field.
func (o *ClientRequestHistoryItem) SetInputDomain(v string) {
	o.InputDomain.Set(&v)
}
// SetInputDomainNil sets the value for InputDomain to be an explicit nil
func (o *ClientRequestHistoryItem) SetInputDomainNil() {
	o.InputDomain.Set(nil)
}

// UnsetInputDomain ensures that no value is present for InputDomain, not even an explicit nil
func (o *ClientRequestHistoryItem) UnsetInputDomain() {
	o.InputDomain.Unset()
}

// GetInputEmail returns the InputEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientRequestHistoryItem) GetInputEmail() string {
	if o == nil || IsNil(o.InputEmail.Get()) {
		var ret string
		return ret
	}
	return *o.InputEmail.Get()
}

// GetInputEmailOk returns a tuple with the InputEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientRequestHistoryItem) GetInputEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InputEmail.Get(), o.InputEmail.IsSet()
}

// HasInputEmail returns a boolean if a field has been set.
func (o *ClientRequestHistoryItem) HasInputEmail() bool {
	if o != nil && o.InputEmail.IsSet() {
		return true
	}

	return false
}

// SetInputEmail gets a reference to the given NullableString and assigns it to the InputEmail field.
func (o *ClientRequestHistoryItem) SetInputEmail(v string) {
	o.InputEmail.Set(&v)
}
// SetInputEmailNil sets the value for InputEmail to be an explicit nil
func (o *ClientRequestHistoryItem) SetInputEmailNil() {
	o.InputEmail.Set(nil)
}

// UnsetInputEmail ensures that no value is present for InputEmail, not even an explicit nil
func (o *ClientRequestHistoryItem) UnsetInputEmail() {
	o.InputEmail.Unset()
}

// GetInputLabel returns the InputLabel field value
func (o *ClientRequestHistoryItem) GetInputLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InputLabel
}

// GetInputLabelOk returns a tuple with the InputLabel field value
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryItem) GetInputLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InputLabel, true
}

// SetInputLabel sets field value
func (o *ClientRequestHistoryItem) SetInputLabel(v string) {
	o.InputLabel = v
}

// GetState returns the State field value
func (o *ClientRequestHistoryItem) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryItem) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ClientRequestHistoryItem) SetState(v string) {
	o.State = v
}

// GetOutcome returns the Outcome field value
func (o *ClientRequestHistoryItem) GetOutcome() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryItem) GetOutcomeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outcome, true
}

// SetOutcome sets field value
func (o *ClientRequestHistoryItem) SetOutcome(v string) {
	o.Outcome = v
}

// GetResolvedAddress returns the ResolvedAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientRequestHistoryItem) GetResolvedAddress() string {
	if o == nil || IsNil(o.ResolvedAddress.Get()) {
		var ret string
		return ret
	}
	return *o.ResolvedAddress.Get()
}

// GetResolvedAddressOk returns a tuple with the ResolvedAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientRequestHistoryItem) GetResolvedAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResolvedAddress.Get(), o.ResolvedAddress.IsSet()
}

// HasResolvedAddress returns a boolean if a field has been set.
func (o *ClientRequestHistoryItem) HasResolvedAddress() bool {
	if o != nil && o.ResolvedAddress.IsSet() {
		return true
	}

	return false
}

// SetResolvedAddress gets a reference to the given NullableString and assigns it to the ResolvedAddress field.
func (o *ClientRequestHistoryItem) SetResolvedAddress(v string) {
	o.ResolvedAddress.Set(&v)
}
// SetResolvedAddressNil sets the value for ResolvedAddress to be an explicit nil
func (o *ClientRequestHistoryItem) SetResolvedAddressNil() {
	o.ResolvedAddress.Set(nil)
}

// UnsetResolvedAddress ensures that no value is present for ResolvedAddress, not even an explicit nil
func (o *ClientRequestHistoryItem) UnsetResolvedAddress() {
	o.ResolvedAddress.Unset()
}

// GetDurationMs returns the DurationMs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientRequestHistoryItem) GetDurationMs() int32 {
	if o == nil || IsNil(o.DurationMs.Get()) {
		var ret int32
		return ret
	}
	return *o.DurationMs.Get()
}

// GetDurationMsOk returns a tuple with the DurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientRequestHistoryItem) GetDurationMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DurationMs.Get(), o.DurationMs.IsSet()
}

// HasDurationMs returns a boolean if a field has been set.
func (o *ClientRequestHistoryItem) HasDurationMs() bool {
	if o != nil && o.DurationMs.IsSet() {
		return true
	}

	return false
}

// SetDurationMs gets a reference to the given NullableInt32 and assigns it to the DurationMs field.
func (o *ClientRequestHistoryItem) SetDurationMs(v int32) {
	o.DurationMs.Set(&v)
}
// SetDurationMsNil sets the value for DurationMs to be an explicit nil
func (o *ClientRequestHistoryItem) SetDurationMsNil() {
	o.DurationMs.Set(nil)
}

// UnsetDurationMs ensures that no value is present for DurationMs, not even an explicit nil
func (o *ClientRequestHistoryItem) UnsetDurationMs() {
	o.DurationMs.Unset()
}

// GetProvider returns the Provider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientRequestHistoryItem) GetProvider() string {
	if o == nil || IsNil(o.Provider.Get()) {
		var ret string
		return ret
	}
	return *o.Provider.Get()
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientRequestHistoryItem) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provider.Get(), o.Provider.IsSet()
}

// HasProvider returns a boolean if a field has been set.
func (o *ClientRequestHistoryItem) HasProvider() bool {
	if o != nil && o.Provider.IsSet() {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullableString and assigns it to the Provider field.
func (o *ClientRequestHistoryItem) SetProvider(v string) {
	o.Provider.Set(&v)
}
// SetProviderNil sets the value for Provider to be an explicit nil
func (o *ClientRequestHistoryItem) SetProviderNil() {
	o.Provider.Set(nil)
}

// UnsetProvider ensures that no value is present for Provider, not even an explicit nil
func (o *ClientRequestHistoryItem) UnsetProvider() {
	o.Provider.Unset()
}

// GetIdentityProviders returns the IdentityProviders field value if set, zero value otherwise.
func (o *ClientRequestHistoryItem) GetIdentityProviders() []map[string]interface{} {
	if o == nil || IsNil(o.IdentityProviders) {
		var ret []map[string]interface{}
		return ret
	}
	return o.IdentityProviders
}

// GetIdentityProvidersOk returns a tuple with the IdentityProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryItem) GetIdentityProvidersOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.IdentityProviders) {
		return nil, false
	}
	return o.IdentityProviders, true
}

// HasIdentityProviders returns a boolean if a field has been set.
func (o *ClientRequestHistoryItem) HasIdentityProviders() bool {
	if o != nil && !IsNil(o.IdentityProviders) {
		return true
	}

	return false
}

// SetIdentityProviders gets a reference to the given []map[string]interface{} and assigns it to the IdentityProviders field.
func (o *ClientRequestHistoryItem) SetIdentityProviders(v []map[string]interface{}) {
	o.IdentityProviders = v
}

// GetMxHosts returns the MxHosts field value if set, zero value otherwise.
func (o *ClientRequestHistoryItem) GetMxHosts() []string {
	if o == nil || IsNil(o.MxHosts) {
		var ret []string
		return ret
	}
	return o.MxHosts
}

// GetMxHostsOk returns a tuple with the MxHosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryItem) GetMxHostsOk() ([]string, bool) {
	if o == nil || IsNil(o.MxHosts) {
		return nil, false
	}
	return o.MxHosts, true
}

// HasMxHosts returns a boolean if a field has been set.
func (o *ClientRequestHistoryItem) HasMxHosts() bool {
	if o != nil && !IsNil(o.MxHosts) {
		return true
	}

	return false
}

// SetMxHosts gets a reference to the given []string and assigns it to the MxHosts field.
func (o *ClientRequestHistoryItem) SetMxHosts(v []string) {
	o.MxHosts = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ClientRequestHistoryItem) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryItem) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ClientRequestHistoryItem) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *ClientRequestHistoryItem) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetIsAlias returns the IsAlias field value if set, zero value otherwise.
func (o *ClientRequestHistoryItem) GetIsAlias() bool {
	if o == nil || IsNil(o.IsAlias) {
		var ret bool
		return ret
	}
	return *o.IsAlias
}

// GetIsAliasOk returns a tuple with the IsAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryItem) GetIsAliasOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAlias) {
		return nil, false
	}
	return o.IsAlias, true
}

// HasIsAlias returns a boolean if a field has been set.
func (o *ClientRequestHistoryItem) HasIsAlias() bool {
	if o != nil && !IsNil(o.IsAlias) {
		return true
	}

	return false
}

// SetIsAlias gets a reference to the given bool and assigns it to the IsAlias field.
func (o *ClientRequestHistoryItem) SetIsAlias(v bool) {
	o.IsAlias = &v
}

// GetIsCatchall returns the IsCatchall field value if set, zero value otherwise.
func (o *ClientRequestHistoryItem) GetIsCatchall() bool {
	if o == nil || IsNil(o.IsCatchall) {
		var ret bool
		return ret
	}
	return *o.IsCatchall
}

// GetIsCatchallOk returns a tuple with the IsCatchall field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryItem) GetIsCatchallOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCatchall) {
		return nil, false
	}
	return o.IsCatchall, true
}

// HasIsCatchall returns a boolean if a field has been set.
func (o *ClientRequestHistoryItem) HasIsCatchall() bool {
	if o != nil && !IsNil(o.IsCatchall) {
		return true
	}

	return false
}

// SetIsCatchall gets a reference to the given bool and assigns it to the IsCatchall field.
func (o *ClientRequestHistoryItem) SetIsCatchall(v bool) {
	o.IsCatchall = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientRequestHistoryItem) GetRequestId() string {
	if o == nil || IsNil(o.RequestId.Get()) {
		var ret string
		return ret
	}
	return *o.RequestId.Get()
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientRequestHistoryItem) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestId.Get(), o.RequestId.IsSet()
}

// HasRequestId returns a boolean if a field has been set.
func (o *ClientRequestHistoryItem) HasRequestId() bool {
	if o != nil && o.RequestId.IsSet() {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given NullableString and assigns it to the RequestId field.
func (o *ClientRequestHistoryItem) SetRequestId(v string) {
	o.RequestId.Set(&v)
}
// SetRequestIdNil sets the value for RequestId to be an explicit nil
func (o *ClientRequestHistoryItem) SetRequestIdNil() {
	o.RequestId.Set(nil)
}

// UnsetRequestId ensures that no value is present for RequestId, not even an explicit nil
func (o *ClientRequestHistoryItem) UnsetRequestId() {
	o.RequestId.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *ClientRequestHistoryItem) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ClientRequestHistoryItem) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ClientRequestHistoryItem) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o ClientRequestHistoryItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientRequestHistoryItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["request_type"] = o.RequestType
	if o.InputName.IsSet() {
		toSerialize["input_name"] = o.InputName.Get()
	}
	if o.InputDomain.IsSet() {
		toSerialize["input_domain"] = o.InputDomain.Get()
	}
	if o.InputEmail.IsSet() {
		toSerialize["input_email"] = o.InputEmail.Get()
	}
	toSerialize["input_label"] = o.InputLabel
	toSerialize["state"] = o.State
	toSerialize["outcome"] = o.Outcome
	if o.ResolvedAddress.IsSet() {
		toSerialize["resolved_address"] = o.ResolvedAddress.Get()
	}
	if o.DurationMs.IsSet() {
		toSerialize["duration_ms"] = o.DurationMs.Get()
	}
	if o.Provider.IsSet() {
		toSerialize["provider"] = o.Provider.Get()
	}
	if !IsNil(o.IdentityProviders) {
		toSerialize["identity_providers"] = o.IdentityProviders
	}
	if !IsNil(o.MxHosts) {
		toSerialize["mx_hosts"] = o.MxHosts
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.IsAlias) {
		toSerialize["is_alias"] = o.IsAlias
	}
	if !IsNil(o.IsCatchall) {
		toSerialize["is_catchall"] = o.IsCatchall
	}
	if o.RequestId.IsSet() {
		toSerialize["request_id"] = o.RequestId.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *ClientRequestHistoryItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"request_type",
		"input_label",
		"state",
		"outcome",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientRequestHistoryItem := _ClientRequestHistoryItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClientRequestHistoryItem)

	if err != nil {
		return err
	}

	*o = ClientRequestHistoryItem(varClientRequestHistoryItem)

	return err
}

type NullableClientRequestHistoryItem struct {
	value *ClientRequestHistoryItem
	isSet bool
}

func (v NullableClientRequestHistoryItem) Get() *ClientRequestHistoryItem {
	return v.value
}

func (v *NullableClientRequestHistoryItem) Set(val *ClientRequestHistoryItem) {
	v.value = val
	v.isSet = true
}

func (v NullableClientRequestHistoryItem) IsSet() bool {
	return v.isSet
}

func (v *NullableClientRequestHistoryItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientRequestHistoryItem(val *ClientRequestHistoryItem) *NullableClientRequestHistoryItem {
	return &NullableClientRequestHistoryItem{value: val, isSet: true}
}

func (v NullableClientRequestHistoryItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientRequestHistoryItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


